/**
 *
 *  Commits.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace teams_manager
{

class Commits
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _html_url;
        static const std::string _commit_sha;
        static const std::string _user_id;
        static const std::string _user_name;
        static const std::string _github_author_id;
        static const std::string _github_author_login;
        static const std::string _message;
        static const std::string _github_repository_id;
        static const std::string _github_repository_name;
        static const std::string _committed_at;
        static const std::string _project_id;
        static const std::string _milestone_id;
        static const std::string _task_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Commits(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Commits(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Commits(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Commits() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column html_url  */
    ///Get the value of the column html_url, returns the default value if the column is null
    const std::string &getValueOfHtmlUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHtmlUrl() const noexcept;
    ///Set the value of the column html_url
    void setHtmlUrl(const std::string &pHtmlUrl) noexcept;
    void setHtmlUrl(std::string &&pHtmlUrl) noexcept;

    /**  For column commit_sha  */
    ///Get the value of the column commit_sha, returns the default value if the column is null
    const std::string &getValueOfCommitSha() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCommitSha() const noexcept;
    ///Set the value of the column commit_sha
    void setCommitSha(const std::string &pCommitSha) noexcept;
    void setCommitSha(std::string &&pCommitSha) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const std::string &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const std::string &pUserId) noexcept;
    void setUserId(std::string &&pUserId) noexcept;
    void setUserIdToNull() noexcept;

    /**  For column user_name  */
    ///Get the value of the column user_name, returns the default value if the column is null
    const std::string &getValueOfUserName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUserName() const noexcept;
    ///Set the value of the column user_name
    void setUserName(const std::string &pUserName) noexcept;
    void setUserName(std::string &&pUserName) noexcept;
    void setUserNameToNull() noexcept;

    /**  For column github_author_id  */
    ///Get the value of the column github_author_id, returns the default value if the column is null
    const int64_t &getValueOfGithubAuthorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getGithubAuthorId() const noexcept;
    ///Set the value of the column github_author_id
    void setGithubAuthorId(const int64_t &pGithubAuthorId) noexcept;

    /**  For column github_author_login  */
    ///Get the value of the column github_author_login, returns the default value if the column is null
    const std::string &getValueOfGithubAuthorLogin() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGithubAuthorLogin() const noexcept;
    ///Set the value of the column github_author_login
    void setGithubAuthorLogin(const std::string &pGithubAuthorLogin) noexcept;
    void setGithubAuthorLogin(std::string &&pGithubAuthorLogin) noexcept;

    /**  For column message  */
    ///Get the value of the column message, returns the default value if the column is null
    const std::string &getValueOfMessage() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMessage() const noexcept;
    ///Set the value of the column message
    void setMessage(const std::string &pMessage) noexcept;
    void setMessage(std::string &&pMessage) noexcept;

    /**  For column github_repository_id  */
    ///Get the value of the column github_repository_id, returns the default value if the column is null
    const int64_t &getValueOfGithubRepositoryId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getGithubRepositoryId() const noexcept;
    ///Set the value of the column github_repository_id
    void setGithubRepositoryId(const int64_t &pGithubRepositoryId) noexcept;

    /**  For column github_repository_name  */
    ///Get the value of the column github_repository_name, returns the default value if the column is null
    const std::string &getValueOfGithubRepositoryName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGithubRepositoryName() const noexcept;
    ///Set the value of the column github_repository_name
    void setGithubRepositoryName(const std::string &pGithubRepositoryName) noexcept;
    void setGithubRepositoryName(std::string &&pGithubRepositoryName) noexcept;

    /**  For column committed_at  */
    ///Get the value of the column committed_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCommittedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCommittedAt() const noexcept;
    ///Set the value of the column committed_at
    void setCommittedAt(const ::trantor::Date &pCommittedAt) noexcept;

    /**  For column project_id  */
    ///Get the value of the column project_id, returns the default value if the column is null
    const std::string &getValueOfProjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectId() const noexcept;
    ///Set the value of the column project_id
    void setProjectId(const std::string &pProjectId) noexcept;
    void setProjectId(std::string &&pProjectId) noexcept;
    void setProjectIdToNull() noexcept;

    /**  For column milestone_id  */
    ///Get the value of the column milestone_id, returns the default value if the column is null
    const std::string &getValueOfMilestoneId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMilestoneId() const noexcept;
    ///Set the value of the column milestone_id
    void setMilestoneId(const std::string &pMilestoneId) noexcept;
    void setMilestoneId(std::string &&pMilestoneId) noexcept;
    void setMilestoneIdToNull() noexcept;

    /**  For column task_id  */
    ///Get the value of the column task_id, returns the default value if the column is null
    const std::string &getValueOfTaskId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaskId() const noexcept;
    ///Set the value of the column task_id
    void setTaskId(const std::string &pTaskId) noexcept;
    void setTaskId(std::string &&pTaskId) noexcept;
    void setTaskIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Commits>;
    friend drogon::orm::BaseBuilder<Commits, true, true>;
    friend drogon::orm::BaseBuilder<Commits, true, false>;
    friend drogon::orm::BaseBuilder<Commits, false, true>;
    friend drogon::orm::BaseBuilder<Commits, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Commits>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> htmlUrl_;
    std::shared_ptr<std::string> commitSha_;
    std::shared_ptr<std::string> userId_;
    std::shared_ptr<std::string> userName_;
    std::shared_ptr<int64_t> githubAuthorId_;
    std::shared_ptr<std::string> githubAuthorLogin_;
    std::shared_ptr<std::string> message_;
    std::shared_ptr<int64_t> githubRepositoryId_;
    std::shared_ptr<std::string> githubRepositoryName_;
    std::shared_ptr<::trantor::Date> committedAt_;
    std::shared_ptr<std::string> projectId_;
    std::shared_ptr<std::string> milestoneId_;
    std::shared_ptr<std::string> taskId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "html_url,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "commit_sha,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "user_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "github_author_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "github_author_login,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "message,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "github_repository_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "github_repository_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "committed_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "project_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "milestone_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "task_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace teams_manager
} // namespace drogon_model
