/**
 *
 *  MentorsTasks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MentorsTasks.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string MentorsTasks::Cols::_task_id = "\"task_id\"";
const std::string MentorsTasks::Cols::_user_id = "\"user_id\"";
const std::string MentorsTasks::Cols::_user_name = "\"user_name\"";
const std::vector<std::string> MentorsTasks::primaryKeyName = {"task_id","user_id"};
const bool MentorsTasks::hasPrimaryKey = true;
const std::string MentorsTasks::tableName = "\"mentors_tasks\"";

const std::vector<typename MentorsTasks::MetaData> MentorsTasks::metaData_={
{"task_id","std::string","uuid",0,0,1,1},
{"user_id","std::string","uuid",0,0,1,1},
{"user_name","std::string","character varying",100,0,0,1}
};
const std::string &MentorsTasks::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MentorsTasks::MentorsTasks(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(r["task_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(r["user_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            taskId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

MentorsTasks::MentorsTasks(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

MentorsTasks::MentorsTasks(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("user_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(pJson["user_name"].asString());
        }
    }
}

void MentorsTasks::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void MentorsTasks::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("task_id"))
    {
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("user_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(pJson["user_name"].asString());
        }
    }
}

const std::string &MentorsTasks::getValueOfTaskId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(taskId_)
        return *taskId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MentorsTasks::getTaskId() const noexcept
{
    return taskId_;
}
void MentorsTasks::setTaskId(const std::string &pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(pTaskId);
    dirtyFlag_[0] = true;
}
void MentorsTasks::setTaskId(std::string &&pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(std::move(pTaskId));
    dirtyFlag_[0] = true;
}

const std::string &MentorsTasks::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MentorsTasks::getUserId() const noexcept
{
    return userId_;
}
void MentorsTasks::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void MentorsTasks::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}

const std::string &MentorsTasks::getValueOfUserName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userName_)
        return *userName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MentorsTasks::getUserName() const noexcept
{
    return userName_;
}
void MentorsTasks::setUserName(const std::string &pUserName) noexcept
{
    userName_ = std::make_shared<std::string>(pUserName);
    dirtyFlag_[2] = true;
}
void MentorsTasks::setUserName(std::string &&pUserName) noexcept
{
    userName_ = std::make_shared<std::string>(std::move(pUserName));
    dirtyFlag_[2] = true;
}

void MentorsTasks::updateId(const uint64_t id)
{
}
typename MentorsTasks::PrimaryKeyType MentorsTasks::getPrimaryKey() const
{
    return std::make_tuple(*taskId_,*userId_);
}

const std::vector<std::string> &MentorsTasks::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "task_id",
        "user_id",
        "user_name"
    };
    return inCols;
}

void MentorsTasks::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserName())
        {
            binder << getValueOfUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MentorsTasks::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void MentorsTasks::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserName())
        {
            binder << getValueOfUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MentorsTasks::toJson() const
{
    Json::Value ret;
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserName())
    {
        ret["user_name"]=getValueOfUserName();
    }
    else
    {
        ret["user_name"]=Json::Value();
    }
    return ret;
}

std::string MentorsTasks::toString() const
{
    return toJson().toStyledString();
}

Json::Value MentorsTasks::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getTaskId())
            {
                ret[pMasqueradingVector[0]]=getValueOfTaskId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserName())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserName())
    {
        ret["user_name"]=getValueOfUserName();
    }
    else
    {
        ret["user_name"]=Json::Value();
    }
    return ret;
}

bool MentorsTasks::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(0, "task_id", pJson["task_id"], err, true))
            return false;
    }
    else
    {
        err="The task_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_name"))
    {
        if(!validJsonOfField(2, "user_name", pJson["user_name"], err, true))
            return false;
    }
    else
    {
        err="The user_name column cannot be null";
        return false;
    }
    return true;
}
bool MentorsTasks::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MentorsTasks::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(0, "task_id", pJson["task_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_name"))
    {
        if(!validJsonOfField(2, "user_name", pJson["user_name"], err, false))
            return false;
    }
    return true;
}
bool MentorsTasks::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MentorsTasks::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
