/**
 *
 *  MilestoneAcceptanceRecords.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MilestoneAcceptanceRecords.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string MilestoneAcceptanceRecords::Cols::_id = "\"id\"";
const std::string MilestoneAcceptanceRecords::Cols::_milestone_id = "\"milestone_id\"";
const std::string MilestoneAcceptanceRecords::Cols::_acceptor_id = "\"acceptor_id\"";
const std::string MilestoneAcceptanceRecords::Cols::_requested_at = "\"requested_at\"";
const std::string MilestoneAcceptanceRecords::Cols::_accepted = "\"accepted\"";
const std::string MilestoneAcceptanceRecords::Cols::_reject_type_id = "\"reject_type_id\"";
const std::string MilestoneAcceptanceRecords::Cols::_reject_reason = "\"reject_reason\"";
const std::string MilestoneAcceptanceRecords::Cols::_developer_response_type_id = "\"developer_response_type_id\"";
const std::string MilestoneAcceptanceRecords::Cols::_acceptor_comment = "\"acceptor_comment\"";
const std::string MilestoneAcceptanceRecords::Cols::_developer_comment = "\"developer_comment\"";
const std::string MilestoneAcceptanceRecords::Cols::_reviewed_at = "\"reviewed_at\"";
const std::string MilestoneAcceptanceRecords::Cols::_created_at = "\"created_at\"";
const std::string MilestoneAcceptanceRecords::Cols::_updated_at = "\"updated_at\"";
const std::string MilestoneAcceptanceRecords::primaryKeyName = "id";
const bool MilestoneAcceptanceRecords::hasPrimaryKey = true;
const std::string MilestoneAcceptanceRecords::tableName = "\"milestone_acceptance_records\"";

const std::vector<typename MilestoneAcceptanceRecords::MetaData> MilestoneAcceptanceRecords::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"milestone_id","std::string","uuid",0,0,0,1},
{"acceptor_id","std::string","uuid",0,0,0,1},
{"requested_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"accepted","bool","boolean",1,0,0,1},
{"reject_type_id","std::string","uuid",0,0,0,0},
{"reject_reason","std::string","text",0,0,0,0},
{"developer_response_type_id","std::string","uuid",0,0,0,0},
{"acceptor_comment","std::string","text",0,0,0,0},
{"developer_comment","std::string","text",0,0,0,0},
{"reviewed_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &MilestoneAcceptanceRecords::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MilestoneAcceptanceRecords::MilestoneAcceptanceRecords(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["milestone_id"].isNull())
        {
            milestoneId_=std::make_shared<std::string>(r["milestone_id"].as<std::string>());
        }
        if(!r["acceptor_id"].isNull())
        {
            acceptorId_=std::make_shared<std::string>(r["acceptor_id"].as<std::string>());
        }
        if(!r["requested_at"].isNull())
        {
            auto timeStr = r["requested_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["accepted"].isNull())
        {
            accepted_=std::make_shared<bool>(r["accepted"].as<bool>());
        }
        if(!r["reject_type_id"].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(r["reject_type_id"].as<std::string>());
        }
        if(!r["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(r["reject_reason"].as<std::string>());
        }
        if(!r["developer_response_type_id"].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(r["developer_response_type_id"].as<std::string>());
        }
        if(!r["acceptor_comment"].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(r["acceptor_comment"].as<std::string>());
        }
        if(!r["developer_comment"].isNull())
        {
            developerComment_=std::make_shared<std::string>(r["developer_comment"].as<std::string>());
        }
        if(!r["reviewed_at"].isNull())
        {
            auto timeStr = r["reviewed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            milestoneId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            acceptorId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            accepted_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            rejectReason_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            developerComment_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

MilestoneAcceptanceRecords::MilestoneAcceptanceRecords(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            milestoneId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            acceptorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            accepted_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            developerComment_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

MilestoneAcceptanceRecords::MilestoneAcceptanceRecords(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("milestone_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["milestone_id"].isNull())
        {
            milestoneId_=std::make_shared<std::string>(pJson["milestone_id"].asString());
        }
    }
    if(pJson.isMember("acceptor_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["acceptor_id"].isNull())
        {
            acceptorId_=std::make_shared<std::string>(pJson["acceptor_id"].asString());
        }
    }
    if(pJson.isMember("requested_at"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["requested_at"].isNull())
        {
            auto timeStr = pJson["requested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("accepted"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["accepted"].isNull())
        {
            accepted_=std::make_shared<bool>(pJson["accepted"].asBool());
        }
    }
    if(pJson.isMember("reject_type_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["reject_type_id"].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(pJson["reject_type_id"].asString());
        }
    }
    if(pJson.isMember("reject_reason"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson["reject_reason"].asString());
        }
    }
    if(pJson.isMember("developer_response_type_id"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["developer_response_type_id"].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(pJson["developer_response_type_id"].asString());
        }
    }
    if(pJson.isMember("acceptor_comment"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["acceptor_comment"].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(pJson["acceptor_comment"].asString());
        }
    }
    if(pJson.isMember("developer_comment"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["developer_comment"].isNull())
        {
            developerComment_=std::make_shared<std::string>(pJson["developer_comment"].asString());
        }
    }
    if(pJson.isMember("reviewed_at"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["reviewed_at"].isNull())
        {
            auto timeStr = pJson["reviewed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MilestoneAcceptanceRecords::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            milestoneId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            acceptorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            accepted_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            developerComment_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MilestoneAcceptanceRecords::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("milestone_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["milestone_id"].isNull())
        {
            milestoneId_=std::make_shared<std::string>(pJson["milestone_id"].asString());
        }
    }
    if(pJson.isMember("acceptor_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["acceptor_id"].isNull())
        {
            acceptorId_=std::make_shared<std::string>(pJson["acceptor_id"].asString());
        }
    }
    if(pJson.isMember("requested_at"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["requested_at"].isNull())
        {
            auto timeStr = pJson["requested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("accepted"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["accepted"].isNull())
        {
            accepted_=std::make_shared<bool>(pJson["accepted"].asBool());
        }
    }
    if(pJson.isMember("reject_type_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["reject_type_id"].isNull())
        {
            rejectTypeId_=std::make_shared<std::string>(pJson["reject_type_id"].asString());
        }
    }
    if(pJson.isMember("reject_reason"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson["reject_reason"].asString());
        }
    }
    if(pJson.isMember("developer_response_type_id"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["developer_response_type_id"].isNull())
        {
            developerResponseTypeId_=std::make_shared<std::string>(pJson["developer_response_type_id"].asString());
        }
    }
    if(pJson.isMember("acceptor_comment"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["acceptor_comment"].isNull())
        {
            acceptorComment_=std::make_shared<std::string>(pJson["acceptor_comment"].asString());
        }
    }
    if(pJson.isMember("developer_comment"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["developer_comment"].isNull())
        {
            developerComment_=std::make_shared<std::string>(pJson["developer_comment"].asString());
        }
    }
    if(pJson.isMember("reviewed_at"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["reviewed_at"].isNull())
        {
            auto timeStr = pJson["reviewed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reviewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &MilestoneAcceptanceRecords::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getId() const noexcept
{
    return id_;
}
void MilestoneAcceptanceRecords::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void MilestoneAcceptanceRecords::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename MilestoneAcceptanceRecords::PrimaryKeyType & MilestoneAcceptanceRecords::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &MilestoneAcceptanceRecords::getValueOfMilestoneId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(milestoneId_)
        return *milestoneId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getMilestoneId() const noexcept
{
    return milestoneId_;
}
void MilestoneAcceptanceRecords::setMilestoneId(const std::string &pMilestoneId) noexcept
{
    milestoneId_ = std::make_shared<std::string>(pMilestoneId);
    dirtyFlag_[1] = true;
}
void MilestoneAcceptanceRecords::setMilestoneId(std::string &&pMilestoneId) noexcept
{
    milestoneId_ = std::make_shared<std::string>(std::move(pMilestoneId));
    dirtyFlag_[1] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfAcceptorId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(acceptorId_)
        return *acceptorId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getAcceptorId() const noexcept
{
    return acceptorId_;
}
void MilestoneAcceptanceRecords::setAcceptorId(const std::string &pAcceptorId) noexcept
{
    acceptorId_ = std::make_shared<std::string>(pAcceptorId);
    dirtyFlag_[2] = true;
}
void MilestoneAcceptanceRecords::setAcceptorId(std::string &&pAcceptorId) noexcept
{
    acceptorId_ = std::make_shared<std::string>(std::move(pAcceptorId));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &MilestoneAcceptanceRecords::getValueOfRequestedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(requestedAt_)
        return *requestedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MilestoneAcceptanceRecords::getRequestedAt() const noexcept
{
    return requestedAt_;
}
void MilestoneAcceptanceRecords::setRequestedAt(const ::trantor::Date &pRequestedAt) noexcept
{
    requestedAt_ = std::make_shared<::trantor::Date>(pRequestedAt);
    dirtyFlag_[3] = true;
}

const bool &MilestoneAcceptanceRecords::getValueOfAccepted() const noexcept
{
    static const bool defaultValue = bool();
    if(accepted_)
        return *accepted_;
    return defaultValue;
}
const std::shared_ptr<bool> &MilestoneAcceptanceRecords::getAccepted() const noexcept
{
    return accepted_;
}
void MilestoneAcceptanceRecords::setAccepted(const bool &pAccepted) noexcept
{
    accepted_ = std::make_shared<bool>(pAccepted);
    dirtyFlag_[4] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfRejectTypeId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rejectTypeId_)
        return *rejectTypeId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getRejectTypeId() const noexcept
{
    return rejectTypeId_;
}
void MilestoneAcceptanceRecords::setRejectTypeId(const std::string &pRejectTypeId) noexcept
{
    rejectTypeId_ = std::make_shared<std::string>(pRejectTypeId);
    dirtyFlag_[5] = true;
}
void MilestoneAcceptanceRecords::setRejectTypeId(std::string &&pRejectTypeId) noexcept
{
    rejectTypeId_ = std::make_shared<std::string>(std::move(pRejectTypeId));
    dirtyFlag_[5] = true;
}
void MilestoneAcceptanceRecords::setRejectTypeIdToNull() noexcept
{
    rejectTypeId_.reset();
    dirtyFlag_[5] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfRejectReason() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rejectReason_)
        return *rejectReason_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getRejectReason() const noexcept
{
    return rejectReason_;
}
void MilestoneAcceptanceRecords::setRejectReason(const std::string &pRejectReason) noexcept
{
    rejectReason_ = std::make_shared<std::string>(pRejectReason);
    dirtyFlag_[6] = true;
}
void MilestoneAcceptanceRecords::setRejectReason(std::string &&pRejectReason) noexcept
{
    rejectReason_ = std::make_shared<std::string>(std::move(pRejectReason));
    dirtyFlag_[6] = true;
}
void MilestoneAcceptanceRecords::setRejectReasonToNull() noexcept
{
    rejectReason_.reset();
    dirtyFlag_[6] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfDeveloperResponseTypeId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(developerResponseTypeId_)
        return *developerResponseTypeId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getDeveloperResponseTypeId() const noexcept
{
    return developerResponseTypeId_;
}
void MilestoneAcceptanceRecords::setDeveloperResponseTypeId(const std::string &pDeveloperResponseTypeId) noexcept
{
    developerResponseTypeId_ = std::make_shared<std::string>(pDeveloperResponseTypeId);
    dirtyFlag_[7] = true;
}
void MilestoneAcceptanceRecords::setDeveloperResponseTypeId(std::string &&pDeveloperResponseTypeId) noexcept
{
    developerResponseTypeId_ = std::make_shared<std::string>(std::move(pDeveloperResponseTypeId));
    dirtyFlag_[7] = true;
}
void MilestoneAcceptanceRecords::setDeveloperResponseTypeIdToNull() noexcept
{
    developerResponseTypeId_.reset();
    dirtyFlag_[7] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfAcceptorComment() const noexcept
{
    static const std::string defaultValue = std::string();
    if(acceptorComment_)
        return *acceptorComment_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getAcceptorComment() const noexcept
{
    return acceptorComment_;
}
void MilestoneAcceptanceRecords::setAcceptorComment(const std::string &pAcceptorComment) noexcept
{
    acceptorComment_ = std::make_shared<std::string>(pAcceptorComment);
    dirtyFlag_[8] = true;
}
void MilestoneAcceptanceRecords::setAcceptorComment(std::string &&pAcceptorComment) noexcept
{
    acceptorComment_ = std::make_shared<std::string>(std::move(pAcceptorComment));
    dirtyFlag_[8] = true;
}
void MilestoneAcceptanceRecords::setAcceptorCommentToNull() noexcept
{
    acceptorComment_.reset();
    dirtyFlag_[8] = true;
}

const std::string &MilestoneAcceptanceRecords::getValueOfDeveloperComment() const noexcept
{
    static const std::string defaultValue = std::string();
    if(developerComment_)
        return *developerComment_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MilestoneAcceptanceRecords::getDeveloperComment() const noexcept
{
    return developerComment_;
}
void MilestoneAcceptanceRecords::setDeveloperComment(const std::string &pDeveloperComment) noexcept
{
    developerComment_ = std::make_shared<std::string>(pDeveloperComment);
    dirtyFlag_[9] = true;
}
void MilestoneAcceptanceRecords::setDeveloperComment(std::string &&pDeveloperComment) noexcept
{
    developerComment_ = std::make_shared<std::string>(std::move(pDeveloperComment));
    dirtyFlag_[9] = true;
}
void MilestoneAcceptanceRecords::setDeveloperCommentToNull() noexcept
{
    developerComment_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &MilestoneAcceptanceRecords::getValueOfReviewedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(reviewedAt_)
        return *reviewedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MilestoneAcceptanceRecords::getReviewedAt() const noexcept
{
    return reviewedAt_;
}
void MilestoneAcceptanceRecords::setReviewedAt(const ::trantor::Date &pReviewedAt) noexcept
{
    reviewedAt_ = std::make_shared<::trantor::Date>(pReviewedAt);
    dirtyFlag_[10] = true;
}
void MilestoneAcceptanceRecords::setReviewedAtToNull() noexcept
{
    reviewedAt_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &MilestoneAcceptanceRecords::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MilestoneAcceptanceRecords::getCreatedAt() const noexcept
{
    return createdAt_;
}
void MilestoneAcceptanceRecords::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[11] = true;
}

const ::trantor::Date &MilestoneAcceptanceRecords::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MilestoneAcceptanceRecords::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void MilestoneAcceptanceRecords::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[12] = true;
}

void MilestoneAcceptanceRecords::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MilestoneAcceptanceRecords::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "milestone_id",
        "acceptor_id",
        "requested_at",
        "accepted",
        "reject_type_id",
        "reject_reason",
        "developer_response_type_id",
        "acceptor_comment",
        "developer_comment",
        "reviewed_at",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void MilestoneAcceptanceRecords::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getMilestoneId())
        {
            binder << getValueOfMilestoneId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAcceptorId())
        {
            binder << getValueOfAcceptorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRequestedAt())
        {
            binder << getValueOfRequestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAccepted())
        {
            binder << getValueOfAccepted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRejectTypeId())
        {
            binder << getValueOfRejectTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRejectReason())
        {
            binder << getValueOfRejectReason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeveloperResponseTypeId())
        {
            binder << getValueOfDeveloperResponseTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAcceptorComment())
        {
            binder << getValueOfAcceptorComment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDeveloperComment())
        {
            binder << getValueOfDeveloperComment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReviewedAt())
        {
            binder << getValueOfReviewedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MilestoneAcceptanceRecords::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void MilestoneAcceptanceRecords::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getMilestoneId())
        {
            binder << getValueOfMilestoneId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAcceptorId())
        {
            binder << getValueOfAcceptorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRequestedAt())
        {
            binder << getValueOfRequestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAccepted())
        {
            binder << getValueOfAccepted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRejectTypeId())
        {
            binder << getValueOfRejectTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRejectReason())
        {
            binder << getValueOfRejectReason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeveloperResponseTypeId())
        {
            binder << getValueOfDeveloperResponseTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAcceptorComment())
        {
            binder << getValueOfAcceptorComment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDeveloperComment())
        {
            binder << getValueOfDeveloperComment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReviewedAt())
        {
            binder << getValueOfReviewedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MilestoneAcceptanceRecords::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMilestoneId())
    {
        ret["milestone_id"]=getValueOfMilestoneId();
    }
    else
    {
        ret["milestone_id"]=Json::Value();
    }
    if(getAcceptorId())
    {
        ret["acceptor_id"]=getValueOfAcceptorId();
    }
    else
    {
        ret["acceptor_id"]=Json::Value();
    }
    if(getRequestedAt())
    {
        ret["requested_at"]=getRequestedAt()->toDbStringLocal();
    }
    else
    {
        ret["requested_at"]=Json::Value();
    }
    if(getAccepted())
    {
        ret["accepted"]=getValueOfAccepted();
    }
    else
    {
        ret["accepted"]=Json::Value();
    }
    if(getRejectTypeId())
    {
        ret["reject_type_id"]=getValueOfRejectTypeId();
    }
    else
    {
        ret["reject_type_id"]=Json::Value();
    }
    if(getRejectReason())
    {
        ret["reject_reason"]=getValueOfRejectReason();
    }
    else
    {
        ret["reject_reason"]=Json::Value();
    }
    if(getDeveloperResponseTypeId())
    {
        ret["developer_response_type_id"]=getValueOfDeveloperResponseTypeId();
    }
    else
    {
        ret["developer_response_type_id"]=Json::Value();
    }
    if(getAcceptorComment())
    {
        ret["acceptor_comment"]=getValueOfAcceptorComment();
    }
    else
    {
        ret["acceptor_comment"]=Json::Value();
    }
    if(getDeveloperComment())
    {
        ret["developer_comment"]=getValueOfDeveloperComment();
    }
    else
    {
        ret["developer_comment"]=Json::Value();
    }
    if(getReviewedAt())
    {
        ret["reviewed_at"]=getReviewedAt()->toDbStringLocal();
    }
    else
    {
        ret["reviewed_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string MilestoneAcceptanceRecords::toString() const
{
    return toJson().toStyledString();
}

Json::Value MilestoneAcceptanceRecords::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMilestoneId())
            {
                ret[pMasqueradingVector[1]]=getValueOfMilestoneId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAcceptorId())
            {
                ret[pMasqueradingVector[2]]=getValueOfAcceptorId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRequestedAt())
            {
                ret[pMasqueradingVector[3]]=getRequestedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAccepted())
            {
                ret[pMasqueradingVector[4]]=getValueOfAccepted();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getRejectTypeId())
            {
                ret[pMasqueradingVector[5]]=getValueOfRejectTypeId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getRejectReason())
            {
                ret[pMasqueradingVector[6]]=getValueOfRejectReason();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDeveloperResponseTypeId())
            {
                ret[pMasqueradingVector[7]]=getValueOfDeveloperResponseTypeId();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getAcceptorComment())
            {
                ret[pMasqueradingVector[8]]=getValueOfAcceptorComment();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getDeveloperComment())
            {
                ret[pMasqueradingVector[9]]=getValueOfDeveloperComment();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getReviewedAt())
            {
                ret[pMasqueradingVector[10]]=getReviewedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[11]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[12]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMilestoneId())
    {
        ret["milestone_id"]=getValueOfMilestoneId();
    }
    else
    {
        ret["milestone_id"]=Json::Value();
    }
    if(getAcceptorId())
    {
        ret["acceptor_id"]=getValueOfAcceptorId();
    }
    else
    {
        ret["acceptor_id"]=Json::Value();
    }
    if(getRequestedAt())
    {
        ret["requested_at"]=getRequestedAt()->toDbStringLocal();
    }
    else
    {
        ret["requested_at"]=Json::Value();
    }
    if(getAccepted())
    {
        ret["accepted"]=getValueOfAccepted();
    }
    else
    {
        ret["accepted"]=Json::Value();
    }
    if(getRejectTypeId())
    {
        ret["reject_type_id"]=getValueOfRejectTypeId();
    }
    else
    {
        ret["reject_type_id"]=Json::Value();
    }
    if(getRejectReason())
    {
        ret["reject_reason"]=getValueOfRejectReason();
    }
    else
    {
        ret["reject_reason"]=Json::Value();
    }
    if(getDeveloperResponseTypeId())
    {
        ret["developer_response_type_id"]=getValueOfDeveloperResponseTypeId();
    }
    else
    {
        ret["developer_response_type_id"]=Json::Value();
    }
    if(getAcceptorComment())
    {
        ret["acceptor_comment"]=getValueOfAcceptorComment();
    }
    else
    {
        ret["acceptor_comment"]=Json::Value();
    }
    if(getDeveloperComment())
    {
        ret["developer_comment"]=getValueOfDeveloperComment();
    }
    else
    {
        ret["developer_comment"]=Json::Value();
    }
    if(getReviewedAt())
    {
        ret["reviewed_at"]=getReviewedAt()->toDbStringLocal();
    }
    else
    {
        ret["reviewed_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool MilestoneAcceptanceRecords::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("milestone_id"))
    {
        if(!validJsonOfField(1, "milestone_id", pJson["milestone_id"], err, true))
            return false;
    }
    else
    {
        err="The milestone_id column cannot be null";
        return false;
    }
    if(pJson.isMember("acceptor_id"))
    {
        if(!validJsonOfField(2, "acceptor_id", pJson["acceptor_id"], err, true))
            return false;
    }
    else
    {
        err="The acceptor_id column cannot be null";
        return false;
    }
    if(pJson.isMember("requested_at"))
    {
        if(!validJsonOfField(3, "requested_at", pJson["requested_at"], err, true))
            return false;
    }
    else
    {
        err="The requested_at column cannot be null";
        return false;
    }
    if(pJson.isMember("accepted"))
    {
        if(!validJsonOfField(4, "accepted", pJson["accepted"], err, true))
            return false;
    }
    else
    {
        err="The accepted column cannot be null";
        return false;
    }
    if(pJson.isMember("reject_type_id"))
    {
        if(!validJsonOfField(5, "reject_type_id", pJson["reject_type_id"], err, true))
            return false;
    }
    if(pJson.isMember("reject_reason"))
    {
        if(!validJsonOfField(6, "reject_reason", pJson["reject_reason"], err, true))
            return false;
    }
    if(pJson.isMember("developer_response_type_id"))
    {
        if(!validJsonOfField(7, "developer_response_type_id", pJson["developer_response_type_id"], err, true))
            return false;
    }
    if(pJson.isMember("acceptor_comment"))
    {
        if(!validJsonOfField(8, "acceptor_comment", pJson["acceptor_comment"], err, true))
            return false;
    }
    if(pJson.isMember("developer_comment"))
    {
        if(!validJsonOfField(9, "developer_comment", pJson["developer_comment"], err, true))
            return false;
    }
    if(pJson.isMember("reviewed_at"))
    {
        if(!validJsonOfField(10, "reviewed_at", pJson["reviewed_at"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    else
    {
        err="The updated_at column cannot be null";
        return false;
    }
    return true;
}
bool MilestoneAcceptanceRecords::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                    const std::vector<std::string> &pMasqueradingVector,
                                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[12] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MilestoneAcceptanceRecords::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("milestone_id"))
    {
        if(!validJsonOfField(1, "milestone_id", pJson["milestone_id"], err, false))
            return false;
    }
    if(pJson.isMember("acceptor_id"))
    {
        if(!validJsonOfField(2, "acceptor_id", pJson["acceptor_id"], err, false))
            return false;
    }
    if(pJson.isMember("requested_at"))
    {
        if(!validJsonOfField(3, "requested_at", pJson["requested_at"], err, false))
            return false;
    }
    if(pJson.isMember("accepted"))
    {
        if(!validJsonOfField(4, "accepted", pJson["accepted"], err, false))
            return false;
    }
    if(pJson.isMember("reject_type_id"))
    {
        if(!validJsonOfField(5, "reject_type_id", pJson["reject_type_id"], err, false))
            return false;
    }
    if(pJson.isMember("reject_reason"))
    {
        if(!validJsonOfField(6, "reject_reason", pJson["reject_reason"], err, false))
            return false;
    }
    if(pJson.isMember("developer_response_type_id"))
    {
        if(!validJsonOfField(7, "developer_response_type_id", pJson["developer_response_type_id"], err, false))
            return false;
    }
    if(pJson.isMember("acceptor_comment"))
    {
        if(!validJsonOfField(8, "acceptor_comment", pJson["acceptor_comment"], err, false))
            return false;
    }
    if(pJson.isMember("developer_comment"))
    {
        if(!validJsonOfField(9, "developer_comment", pJson["developer_comment"], err, false))
            return false;
    }
    if(pJson.isMember("reviewed_at"))
    {
        if(!validJsonOfField(10, "reviewed_at", pJson["reviewed_at"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool MilestoneAcceptanceRecords::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                  const std::vector<std::string> &pMasqueradingVector,
                                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MilestoneAcceptanceRecords::validJsonOfField(size_t index,
                                                  const std::string &fieldName,
                                                  const Json::Value &pJson,
                                                  std::string &err,
                                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
