/**
 *
 *  Milestones.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace teams_manager
{

class Milestones
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _name;
        static const std::string _description;
        static const std::string _project_id;
        static const std::string _project_name;
        static const std::string _team_id;
        static const std::string _team_name;
        static const std::string _tenant_id;
        static const std::string _tenant_name;
        static const std::string _start_date;
        static const std::string _end_date;
        static const std::string _created_at;
        static const std::string _creator_id;
        static const std::string _creator_name;
        static const std::string _concurrency_stamp;
        static const std::string _remark;
        static const std::string _priority;
        static const std::string _estimated_remaining_workdays;
        static const std::string _dependency_milestone_id;
        static const std::string _estimated_start_date;
        static const std::string _estimated_end_date;
        static const std::string _completed;
        static const std::string _is_for_demo;
        static const std::string _completion_date;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Milestones(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Milestones(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Milestones(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Milestones() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column project_id  */
    ///Get the value of the column project_id, returns the default value if the column is null
    const std::string &getValueOfProjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectId() const noexcept;
    ///Set the value of the column project_id
    void setProjectId(const std::string &pProjectId) noexcept;
    void setProjectId(std::string &&pProjectId) noexcept;

    /**  For column project_name  */
    ///Get the value of the column project_name, returns the default value if the column is null
    const std::string &getValueOfProjectName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectName() const noexcept;
    ///Set the value of the column project_name
    void setProjectName(const std::string &pProjectName) noexcept;
    void setProjectName(std::string &&pProjectName) noexcept;
    void setProjectNameToNull() noexcept;

    /**  For column team_id  */
    ///Get the value of the column team_id, returns the default value if the column is null
    const std::string &getValueOfTeamId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeamId() const noexcept;
    ///Set the value of the column team_id
    void setTeamId(const std::string &pTeamId) noexcept;
    void setTeamId(std::string &&pTeamId) noexcept;
    void setTeamIdToNull() noexcept;

    /**  For column team_name  */
    ///Get the value of the column team_name, returns the default value if the column is null
    const std::string &getValueOfTeamName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeamName() const noexcept;
    ///Set the value of the column team_name
    void setTeamName(const std::string &pTeamName) noexcept;
    void setTeamName(std::string &&pTeamName) noexcept;
    void setTeamNameToNull() noexcept;

    /**  For column tenant_id  */
    ///Get the value of the column tenant_id, returns the default value if the column is null
    const std::string &getValueOfTenantId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTenantId() const noexcept;
    ///Set the value of the column tenant_id
    void setTenantId(const std::string &pTenantId) noexcept;
    void setTenantId(std::string &&pTenantId) noexcept;
    void setTenantIdToNull() noexcept;

    /**  For column tenant_name  */
    ///Get the value of the column tenant_name, returns the default value if the column is null
    const std::string &getValueOfTenantName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTenantName() const noexcept;
    ///Set the value of the column tenant_name
    void setTenantName(const std::string &pTenantName) noexcept;
    void setTenantName(std::string &&pTenantName) noexcept;
    void setTenantNameToNull() noexcept;

    /**  For column start_date  */
    ///Get the value of the column start_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfStartDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getStartDate() const noexcept;
    ///Set the value of the column start_date
    void setStartDate(const ::trantor::Date &pStartDate) noexcept;
    void setStartDateToNull() noexcept;

    /**  For column end_date  */
    ///Get the value of the column end_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEndDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEndDate() const noexcept;
    ///Set the value of the column end_date
    void setEndDate(const ::trantor::Date &pEndDate) noexcept;
    void setEndDateToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column creator_id  */
    ///Get the value of the column creator_id, returns the default value if the column is null
    const std::string &getValueOfCreatorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatorId() const noexcept;
    ///Set the value of the column creator_id
    void setCreatorId(const std::string &pCreatorId) noexcept;
    void setCreatorId(std::string &&pCreatorId) noexcept;
    void setCreatorIdToNull() noexcept;

    /**  For column creator_name  */
    ///Get the value of the column creator_name, returns the default value if the column is null
    const std::string &getValueOfCreatorName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatorName() const noexcept;
    ///Set the value of the column creator_name
    void setCreatorName(const std::string &pCreatorName) noexcept;
    void setCreatorName(std::string &&pCreatorName) noexcept;
    void setCreatorNameToNull() noexcept;

    /**  For column concurrency_stamp  */
    ///Get the value of the column concurrency_stamp, returns the default value if the column is null
    const std::string &getValueOfConcurrencyStamp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getConcurrencyStamp() const noexcept;
    ///Set the value of the column concurrency_stamp
    void setConcurrencyStamp(const std::string &pConcurrencyStamp) noexcept;
    void setConcurrencyStamp(std::string &&pConcurrencyStamp) noexcept;

    /**  For column remark  */
    ///Get the value of the column remark, returns the default value if the column is null
    const std::string &getValueOfRemark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRemark() const noexcept;
    ///Set the value of the column remark
    void setRemark(const std::string &pRemark) noexcept;
    void setRemark(std::string &&pRemark) noexcept;
    void setRemarkToNull() noexcept;

    /**  For column priority  */
    ///Get the value of the column priority, returns the default value if the column is null
    const int32_t &getValueOfPriority() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPriority() const noexcept;
    ///Set the value of the column priority
    void setPriority(const int32_t &pPriority) noexcept;

    /**  For column estimated_remaining_workdays  */
    ///Get the value of the column estimated_remaining_workdays, returns the default value if the column is null
    const int32_t &getValueOfEstimatedRemainingWorkdays() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEstimatedRemainingWorkdays() const noexcept;
    ///Set the value of the column estimated_remaining_workdays
    void setEstimatedRemainingWorkdays(const int32_t &pEstimatedRemainingWorkdays) noexcept;

    /**  For column dependency_milestone_id  */
    ///Get the value of the column dependency_milestone_id, returns the default value if the column is null
    const std::string &getValueOfDependencyMilestoneId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDependencyMilestoneId() const noexcept;
    ///Set the value of the column dependency_milestone_id
    void setDependencyMilestoneId(const std::string &pDependencyMilestoneId) noexcept;
    void setDependencyMilestoneId(std::string &&pDependencyMilestoneId) noexcept;
    void setDependencyMilestoneIdToNull() noexcept;

    /**  For column estimated_start_date  */
    ///Get the value of the column estimated_start_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEstimatedStartDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEstimatedStartDate() const noexcept;
    ///Set the value of the column estimated_start_date
    void setEstimatedStartDate(const ::trantor::Date &pEstimatedStartDate) noexcept;
    void setEstimatedStartDateToNull() noexcept;

    /**  For column estimated_end_date  */
    ///Get the value of the column estimated_end_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEstimatedEndDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEstimatedEndDate() const noexcept;
    ///Set the value of the column estimated_end_date
    void setEstimatedEndDate(const ::trantor::Date &pEstimatedEndDate) noexcept;
    void setEstimatedEndDateToNull() noexcept;

    /**  For column completed  */
    ///Get the value of the column completed, returns the default value if the column is null
    const bool &getValueOfCompleted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getCompleted() const noexcept;
    ///Set the value of the column completed
    void setCompleted(const bool &pCompleted) noexcept;

    /**  For column is_for_demo  */
    ///Get the value of the column is_for_demo, returns the default value if the column is null
    const bool &getValueOfIsForDemo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsForDemo() const noexcept;
    ///Set the value of the column is_for_demo
    void setIsForDemo(const bool &pIsForDemo) noexcept;

    /**  For column completion_date  */
    ///Get the value of the column completion_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfCompletionDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCompletionDate() const noexcept;
    ///Set the value of the column completion_date
    void setCompletionDate(const ::trantor::Date &pCompletionDate) noexcept;
    void setCompletionDateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 24;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Milestones>;
    friend drogon::orm::BaseBuilder<Milestones, true, true>;
    friend drogon::orm::BaseBuilder<Milestones, true, false>;
    friend drogon::orm::BaseBuilder<Milestones, false, true>;
    friend drogon::orm::BaseBuilder<Milestones, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Milestones>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> projectId_;
    std::shared_ptr<std::string> projectName_;
    std::shared_ptr<std::string> teamId_;
    std::shared_ptr<std::string> teamName_;
    std::shared_ptr<std::string> tenantId_;
    std::shared_ptr<std::string> tenantName_;
    std::shared_ptr<::trantor::Date> startDate_;
    std::shared_ptr<::trantor::Date> endDate_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<std::string> creatorId_;
    std::shared_ptr<std::string> creatorName_;
    std::shared_ptr<std::string> concurrencyStamp_;
    std::shared_ptr<std::string> remark_;
    std::shared_ptr<int32_t> priority_;
    std::shared_ptr<int32_t> estimatedRemainingWorkdays_;
    std::shared_ptr<std::string> dependencyMilestoneId_;
    std::shared_ptr<::trantor::Date> estimatedStartDate_;
    std::shared_ptr<::trantor::Date> estimatedEndDate_;
    std::shared_ptr<bool> completed_;
    std::shared_ptr<bool> isForDemo_;
    std::shared_ptr<::trantor::Date> completionDate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[24]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "project_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "project_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "team_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "team_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "tenant_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "tenant_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "start_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "end_date,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[11])
        {
            needSelection=true;
        }
        if(dirtyFlag_[12])
        {
            sql += "creator_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "creator_name,";
            ++parametersCount;
        }
        sql += "concurrency_stamp,";
        ++parametersCount;
        if(!dirtyFlag_[14])
        {
            needSelection=true;
        }
        if(dirtyFlag_[15])
        {
            sql += "remark,";
            ++parametersCount;
        }
        sql += "priority,";
        ++parametersCount;
        if(!dirtyFlag_[16])
        {
            needSelection=true;
        }
        sql += "estimated_remaining_workdays,";
        ++parametersCount;
        if(!dirtyFlag_[17])
        {
            needSelection=true;
        }
        if(dirtyFlag_[18])
        {
            sql += "dependency_milestone_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[19])
        {
            sql += "estimated_start_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[20])
        {
            sql += "estimated_end_date,";
            ++parametersCount;
        }
        sql += "completed,";
        ++parametersCount;
        if(!dirtyFlag_[21])
        {
            needSelection=true;
        }
        sql += "is_for_demo,";
        ++parametersCount;
        if(!dirtyFlag_[22])
        {
            needSelection=true;
        }
        if(dirtyFlag_[23])
        {
            sql += "completion_date,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[18])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[20])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[21])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[22])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[23])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace teams_manager
} // namespace drogon_model
