/**
 *
 *  PlanEstimationHistories.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace teams_manager
{

class PlanEstimationHistories
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _plan_id;
        static const std::string _estimation_date;
        static const std::string _complete_date;
        static const std::string _optimistic_estimated_complete_date;
        static const std::string _pessimistic_estimated_complete_date;
        static const std::string _created_at;
        static const std::string _estimated_remaining_workdays;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit PlanEstimationHistories(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit PlanEstimationHistories(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    PlanEstimationHistories(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    PlanEstimationHistories() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column plan_id  */
    ///Get the value of the column plan_id, returns the default value if the column is null
    const std::string &getValueOfPlanId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPlanId() const noexcept;
    ///Set the value of the column plan_id
    void setPlanId(const std::string &pPlanId) noexcept;
    void setPlanId(std::string &&pPlanId) noexcept;

    /**  For column estimation_date  */
    ///Get the value of the column estimation_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEstimationDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEstimationDate() const noexcept;
    ///Set the value of the column estimation_date
    void setEstimationDate(const ::trantor::Date &pEstimationDate) noexcept;

    /**  For column complete_date  */
    ///Get the value of the column complete_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfCompleteDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCompleteDate() const noexcept;
    ///Set the value of the column complete_date
    void setCompleteDate(const ::trantor::Date &pCompleteDate) noexcept;

    /**  For column optimistic_estimated_complete_date  */
    ///Get the value of the column optimistic_estimated_complete_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfOptimisticEstimatedCompleteDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getOptimisticEstimatedCompleteDate() const noexcept;
    ///Set the value of the column optimistic_estimated_complete_date
    void setOptimisticEstimatedCompleteDate(const ::trantor::Date &pOptimisticEstimatedCompleteDate) noexcept;

    /**  For column pessimistic_estimated_complete_date  */
    ///Get the value of the column pessimistic_estimated_complete_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfPessimisticEstimatedCompleteDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getPessimisticEstimatedCompleteDate() const noexcept;
    ///Set the value of the column pessimistic_estimated_complete_date
    void setPessimisticEstimatedCompleteDate(const ::trantor::Date &pPessimisticEstimatedCompleteDate) noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

    /**  For column estimated_remaining_workdays  */
    ///Get the value of the column estimated_remaining_workdays, returns the default value if the column is null
    const int32_t &getValueOfEstimatedRemainingWorkdays() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEstimatedRemainingWorkdays() const noexcept;
    ///Set the value of the column estimated_remaining_workdays
    void setEstimatedRemainingWorkdays(const int32_t &pEstimatedRemainingWorkdays) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<PlanEstimationHistories>;
    friend drogon::orm::BaseBuilder<PlanEstimationHistories, true, true>;
    friend drogon::orm::BaseBuilder<PlanEstimationHistories, true, false>;
    friend drogon::orm::BaseBuilder<PlanEstimationHistories, false, true>;
    friend drogon::orm::BaseBuilder<PlanEstimationHistories, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<PlanEstimationHistories>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> planId_;
    std::shared_ptr<::trantor::Date> estimationDate_;
    std::shared_ptr<::trantor::Date> completeDate_;
    std::shared_ptr<::trantor::Date> optimisticEstimatedCompleteDate_;
    std::shared_ptr<::trantor::Date> pessimisticEstimatedCompleteDate_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<int32_t> estimatedRemainingWorkdays_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "plan_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "estimation_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "complete_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "optimistic_estimated_complete_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "pessimistic_estimated_complete_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "created_at,";
            ++parametersCount;
        }
        sql += "estimated_remaining_workdays,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace teams_manager
} // namespace drogon_model
