/**
 *
 *  PlanEstimationHistories.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PlanEstimationHistories.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string PlanEstimationHistories::Cols::_id = "\"id\"";
const std::string PlanEstimationHistories::Cols::_plan_id = "\"plan_id\"";
const std::string PlanEstimationHistories::Cols::_estimation_date = "\"estimation_date\"";
const std::string PlanEstimationHistories::Cols::_complete_date = "\"complete_date\"";
const std::string PlanEstimationHistories::Cols::_optimistic_estimated_complete_date = "\"optimistic_estimated_complete_date\"";
const std::string PlanEstimationHistories::Cols::_pessimistic_estimated_complete_date = "\"pessimistic_estimated_complete_date\"";
const std::string PlanEstimationHistories::Cols::_created_at = "\"created_at\"";
const std::string PlanEstimationHistories::Cols::_estimated_remaining_workdays = "\"estimated_remaining_workdays\"";
const std::string PlanEstimationHistories::primaryKeyName = "id";
const bool PlanEstimationHistories::hasPrimaryKey = true;
const std::string PlanEstimationHistories::tableName = "\"plan_estimation_histories\"";

const std::vector<typename PlanEstimationHistories::MetaData> PlanEstimationHistories::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"plan_id","std::string","uuid",0,0,0,1},
{"estimation_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"complete_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"optimistic_estimated_complete_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"pessimistic_estimated_complete_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"estimated_remaining_workdays","int32_t","integer",4,0,0,1}
};
const std::string &PlanEstimationHistories::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PlanEstimationHistories::PlanEstimationHistories(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["plan_id"].isNull())
        {
            planId_=std::make_shared<std::string>(r["plan_id"].as<std::string>());
        }
        if(!r["estimation_date"].isNull())
        {
            auto timeStr = r["estimation_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["complete_date"].isNull())
        {
            auto timeStr = r["complete_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["optimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = r["optimistic_estimated_complete_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["pessimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = r["pessimistic_estimated_complete_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["estimated_remaining_workdays"].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>(r["estimated_remaining_workdays"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            planId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

PlanEstimationHistories::PlanEstimationHistories(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            planId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
}

PlanEstimationHistories::PlanEstimationHistories(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("plan_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["plan_id"].isNull())
        {
            planId_=std::make_shared<std::string>(pJson["plan_id"].asString());
        }
    }
    if(pJson.isMember("estimation_date"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["estimation_date"].isNull())
        {
            auto timeStr = pJson["estimation_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("complete_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["complete_date"].isNull())
        {
            auto timeStr = pJson["complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("optimistic_estimated_complete_date"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["optimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = pJson["optimistic_estimated_complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("pessimistic_estimated_complete_date"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["pessimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = pJson["pessimistic_estimated_complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("estimated_remaining_workdays"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["estimated_remaining_workdays"].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>((int32_t)pJson["estimated_remaining_workdays"].asInt64());
        }
    }
}

void PlanEstimationHistories::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            planId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
}

void PlanEstimationHistories::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("plan_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["plan_id"].isNull())
        {
            planId_=std::make_shared<std::string>(pJson["plan_id"].asString());
        }
    }
    if(pJson.isMember("estimation_date"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["estimation_date"].isNull())
        {
            auto timeStr = pJson["estimation_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                estimationDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("complete_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["complete_date"].isNull())
        {
            auto timeStr = pJson["complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                completeDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("optimistic_estimated_complete_date"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["optimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = pJson["optimistic_estimated_complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                optimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("pessimistic_estimated_complete_date"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["pessimistic_estimated_complete_date"].isNull())
        {
            auto timeStr = pJson["pessimistic_estimated_complete_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                pessimisticEstimatedCompleteDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("estimated_remaining_workdays"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["estimated_remaining_workdays"].isNull())
        {
            estimatedRemainingWorkdays_=std::make_shared<int32_t>((int32_t)pJson["estimated_remaining_workdays"].asInt64());
        }
    }
}

const std::string &PlanEstimationHistories::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PlanEstimationHistories::getId() const noexcept
{
    return id_;
}
void PlanEstimationHistories::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void PlanEstimationHistories::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename PlanEstimationHistories::PrimaryKeyType & PlanEstimationHistories::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &PlanEstimationHistories::getValueOfPlanId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(planId_)
        return *planId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PlanEstimationHistories::getPlanId() const noexcept
{
    return planId_;
}
void PlanEstimationHistories::setPlanId(const std::string &pPlanId) noexcept
{
    planId_ = std::make_shared<std::string>(pPlanId);
    dirtyFlag_[1] = true;
}
void PlanEstimationHistories::setPlanId(std::string &&pPlanId) noexcept
{
    planId_ = std::make_shared<std::string>(std::move(pPlanId));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &PlanEstimationHistories::getValueOfEstimationDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(estimationDate_)
        return *estimationDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlanEstimationHistories::getEstimationDate() const noexcept
{
    return estimationDate_;
}
void PlanEstimationHistories::setEstimationDate(const ::trantor::Date &pEstimationDate) noexcept
{
    estimationDate_ = std::make_shared<::trantor::Date>(pEstimationDate);
    dirtyFlag_[2] = true;
}

const ::trantor::Date &PlanEstimationHistories::getValueOfCompleteDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(completeDate_)
        return *completeDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlanEstimationHistories::getCompleteDate() const noexcept
{
    return completeDate_;
}
void PlanEstimationHistories::setCompleteDate(const ::trantor::Date &pCompleteDate) noexcept
{
    completeDate_ = std::make_shared<::trantor::Date>(pCompleteDate);
    dirtyFlag_[3] = true;
}

const ::trantor::Date &PlanEstimationHistories::getValueOfOptimisticEstimatedCompleteDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(optimisticEstimatedCompleteDate_)
        return *optimisticEstimatedCompleteDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlanEstimationHistories::getOptimisticEstimatedCompleteDate() const noexcept
{
    return optimisticEstimatedCompleteDate_;
}
void PlanEstimationHistories::setOptimisticEstimatedCompleteDate(const ::trantor::Date &pOptimisticEstimatedCompleteDate) noexcept
{
    optimisticEstimatedCompleteDate_ = std::make_shared<::trantor::Date>(pOptimisticEstimatedCompleteDate);
    dirtyFlag_[4] = true;
}

const ::trantor::Date &PlanEstimationHistories::getValueOfPessimisticEstimatedCompleteDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(pessimisticEstimatedCompleteDate_)
        return *pessimisticEstimatedCompleteDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlanEstimationHistories::getPessimisticEstimatedCompleteDate() const noexcept
{
    return pessimisticEstimatedCompleteDate_;
}
void PlanEstimationHistories::setPessimisticEstimatedCompleteDate(const ::trantor::Date &pPessimisticEstimatedCompleteDate) noexcept
{
    pessimisticEstimatedCompleteDate_ = std::make_shared<::trantor::Date>(pPessimisticEstimatedCompleteDate);
    dirtyFlag_[5] = true;
}

const ::trantor::Date &PlanEstimationHistories::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlanEstimationHistories::getCreatedAt() const noexcept
{
    return createdAt_;
}
void PlanEstimationHistories::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[6] = true;
}

const int32_t &PlanEstimationHistories::getValueOfEstimatedRemainingWorkdays() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(estimatedRemainingWorkdays_)
        return *estimatedRemainingWorkdays_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PlanEstimationHistories::getEstimatedRemainingWorkdays() const noexcept
{
    return estimatedRemainingWorkdays_;
}
void PlanEstimationHistories::setEstimatedRemainingWorkdays(const int32_t &pEstimatedRemainingWorkdays) noexcept
{
    estimatedRemainingWorkdays_ = std::make_shared<int32_t>(pEstimatedRemainingWorkdays);
    dirtyFlag_[7] = true;
}

void PlanEstimationHistories::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PlanEstimationHistories::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "plan_id",
        "estimation_date",
        "complete_date",
        "optimistic_estimated_complete_date",
        "pessimistic_estimated_complete_date",
        "created_at",
        "estimated_remaining_workdays"
    };
    return inCols;
}

void PlanEstimationHistories::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlanId())
        {
            binder << getValueOfPlanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEstimationDate())
        {
            binder << getValueOfEstimationDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCompleteDate())
        {
            binder << getValueOfCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOptimisticEstimatedCompleteDate())
        {
            binder << getValueOfOptimisticEstimatedCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPessimisticEstimatedCompleteDate())
        {
            binder << getValueOfPessimisticEstimatedCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEstimatedRemainingWorkdays())
        {
            binder << getValueOfEstimatedRemainingWorkdays();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PlanEstimationHistories::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void PlanEstimationHistories::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlanId())
        {
            binder << getValueOfPlanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEstimationDate())
        {
            binder << getValueOfEstimationDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCompleteDate())
        {
            binder << getValueOfCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOptimisticEstimatedCompleteDate())
        {
            binder << getValueOfOptimisticEstimatedCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPessimisticEstimatedCompleteDate())
        {
            binder << getValueOfPessimisticEstimatedCompleteDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEstimatedRemainingWorkdays())
        {
            binder << getValueOfEstimatedRemainingWorkdays();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PlanEstimationHistories::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPlanId())
    {
        ret["plan_id"]=getValueOfPlanId();
    }
    else
    {
        ret["plan_id"]=Json::Value();
    }
    if(getEstimationDate())
    {
        ret["estimation_date"]=getEstimationDate()->toDbStringLocal();
    }
    else
    {
        ret["estimation_date"]=Json::Value();
    }
    if(getCompleteDate())
    {
        ret["complete_date"]=getCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["complete_date"]=Json::Value();
    }
    if(getOptimisticEstimatedCompleteDate())
    {
        ret["optimistic_estimated_complete_date"]=getOptimisticEstimatedCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["optimistic_estimated_complete_date"]=Json::Value();
    }
    if(getPessimisticEstimatedCompleteDate())
    {
        ret["pessimistic_estimated_complete_date"]=getPessimisticEstimatedCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["pessimistic_estimated_complete_date"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getEstimatedRemainingWorkdays())
    {
        ret["estimated_remaining_workdays"]=getValueOfEstimatedRemainingWorkdays();
    }
    else
    {
        ret["estimated_remaining_workdays"]=Json::Value();
    }
    return ret;
}

std::string PlanEstimationHistories::toString() const
{
    return toJson().toStyledString();
}

Json::Value PlanEstimationHistories::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPlanId())
            {
                ret[pMasqueradingVector[1]]=getValueOfPlanId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getEstimationDate())
            {
                ret[pMasqueradingVector[2]]=getEstimationDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCompleteDate())
            {
                ret[pMasqueradingVector[3]]=getCompleteDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getOptimisticEstimatedCompleteDate())
            {
                ret[pMasqueradingVector[4]]=getOptimisticEstimatedCompleteDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getPessimisticEstimatedCompleteDate())
            {
                ret[pMasqueradingVector[5]]=getPessimisticEstimatedCompleteDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[6]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEstimatedRemainingWorkdays())
            {
                ret[pMasqueradingVector[7]]=getValueOfEstimatedRemainingWorkdays();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPlanId())
    {
        ret["plan_id"]=getValueOfPlanId();
    }
    else
    {
        ret["plan_id"]=Json::Value();
    }
    if(getEstimationDate())
    {
        ret["estimation_date"]=getEstimationDate()->toDbStringLocal();
    }
    else
    {
        ret["estimation_date"]=Json::Value();
    }
    if(getCompleteDate())
    {
        ret["complete_date"]=getCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["complete_date"]=Json::Value();
    }
    if(getOptimisticEstimatedCompleteDate())
    {
        ret["optimistic_estimated_complete_date"]=getOptimisticEstimatedCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["optimistic_estimated_complete_date"]=Json::Value();
    }
    if(getPessimisticEstimatedCompleteDate())
    {
        ret["pessimistic_estimated_complete_date"]=getPessimisticEstimatedCompleteDate()->toDbStringLocal();
    }
    else
    {
        ret["pessimistic_estimated_complete_date"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getEstimatedRemainingWorkdays())
    {
        ret["estimated_remaining_workdays"]=getValueOfEstimatedRemainingWorkdays();
    }
    else
    {
        ret["estimated_remaining_workdays"]=Json::Value();
    }
    return ret;
}

bool PlanEstimationHistories::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("plan_id"))
    {
        if(!validJsonOfField(1, "plan_id", pJson["plan_id"], err, true))
            return false;
    }
    else
    {
        err="The plan_id column cannot be null";
        return false;
    }
    if(pJson.isMember("estimation_date"))
    {
        if(!validJsonOfField(2, "estimation_date", pJson["estimation_date"], err, true))
            return false;
    }
    else
    {
        err="The estimation_date column cannot be null";
        return false;
    }
    if(pJson.isMember("complete_date"))
    {
        if(!validJsonOfField(3, "complete_date", pJson["complete_date"], err, true))
            return false;
    }
    else
    {
        err="The complete_date column cannot be null";
        return false;
    }
    if(pJson.isMember("optimistic_estimated_complete_date"))
    {
        if(!validJsonOfField(4, "optimistic_estimated_complete_date", pJson["optimistic_estimated_complete_date"], err, true))
            return false;
    }
    else
    {
        err="The optimistic_estimated_complete_date column cannot be null";
        return false;
    }
    if(pJson.isMember("pessimistic_estimated_complete_date"))
    {
        if(!validJsonOfField(5, "pessimistic_estimated_complete_date", pJson["pessimistic_estimated_complete_date"], err, true))
            return false;
    }
    else
    {
        err="The pessimistic_estimated_complete_date column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, true))
            return false;
    }
    else
    {
        err="The created_at column cannot be null";
        return false;
    }
    if(pJson.isMember("estimated_remaining_workdays"))
    {
        if(!validJsonOfField(7, "estimated_remaining_workdays", pJson["estimated_remaining_workdays"], err, true))
            return false;
    }
    return true;
}
bool PlanEstimationHistories::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                 const std::vector<std::string> &pMasqueradingVector,
                                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PlanEstimationHistories::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("plan_id"))
    {
        if(!validJsonOfField(1, "plan_id", pJson["plan_id"], err, false))
            return false;
    }
    if(pJson.isMember("estimation_date"))
    {
        if(!validJsonOfField(2, "estimation_date", pJson["estimation_date"], err, false))
            return false;
    }
    if(pJson.isMember("complete_date"))
    {
        if(!validJsonOfField(3, "complete_date", pJson["complete_date"], err, false))
            return false;
    }
    if(pJson.isMember("optimistic_estimated_complete_date"))
    {
        if(!validJsonOfField(4, "optimistic_estimated_complete_date", pJson["optimistic_estimated_complete_date"], err, false))
            return false;
    }
    if(pJson.isMember("pessimistic_estimated_complete_date"))
    {
        if(!validJsonOfField(5, "pessimistic_estimated_complete_date", pJson["pessimistic_estimated_complete_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("estimated_remaining_workdays"))
    {
        if(!validJsonOfField(7, "estimated_remaining_workdays", pJson["estimated_remaining_workdays"], err, false))
            return false;
    }
    return true;
}
bool PlanEstimationHistories::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PlanEstimationHistories::validJsonOfField(size_t index,
                                               const std::string &fieldName,
                                               const Json::Value &pJson,
                                               std::string &err,
                                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
