/**
 *
 *  ProjectMetricsHistory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ProjectMetricsHistory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string ProjectMetricsHistory::Cols::_id = "\"id\"";
const std::string ProjectMetricsHistory::Cols::_date = "\"date\"";
const std::string ProjectMetricsHistory::Cols::_task_count = "\"task_count\"";
const std::string ProjectMetricsHistory::Cols::_task_added_count = "\"task_added_count\"";
const std::string ProjectMetricsHistory::Cols::_task_completed_count = "\"task_completed_count\"";
const std::string ProjectMetricsHistory::Cols::_milestone_count = "\"milestone_count\"";
const std::string ProjectMetricsHistory::Cols::_milestone_added_count = "\"milestone_added_count\"";
const std::string ProjectMetricsHistory::Cols::_milestone_completed_count = "\"milestone_completed_count\"";
const std::string ProjectMetricsHistory::Cols::_changed_at = "\"changed_at\"";
const std::string ProjectMetricsHistory::Cols::_project_id = "\"project_id\"";
const std::string ProjectMetricsHistory::primaryKeyName = "id";
const bool ProjectMetricsHistory::hasPrimaryKey = true;
const std::string ProjectMetricsHistory::tableName = "\"project_metrics_history\"";

const std::vector<typename ProjectMetricsHistory::MetaData> ProjectMetricsHistory::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"date","::trantor::Date","date",0,0,0,1},
{"task_count","int32_t","integer",4,0,0,1},
{"task_added_count","int32_t","integer",4,0,0,1},
{"task_completed_count","int32_t","integer",4,0,0,1},
{"milestone_count","int32_t","integer",4,0,0,1},
{"milestone_added_count","int32_t","integer",4,0,0,1},
{"milestone_completed_count","int32_t","integer",4,0,0,1},
{"changed_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"project_id","std::string","uuid",0,0,0,1}
};
const std::string &ProjectMetricsHistory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ProjectMetricsHistory::ProjectMetricsHistory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["date"].isNull())
        {
            auto daysStr = r["date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["task_count"].isNull())
        {
            taskCount_=std::make_shared<int32_t>(r["task_count"].as<int32_t>());
        }
        if(!r["task_added_count"].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>(r["task_added_count"].as<int32_t>());
        }
        if(!r["task_completed_count"].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>(r["task_completed_count"].as<int32_t>());
        }
        if(!r["milestone_count"].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>(r["milestone_count"].as<int32_t>());
        }
        if(!r["milestone_added_count"].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>(r["milestone_added_count"].as<int32_t>());
        }
        if(!r["milestone_completed_count"].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>(r["milestone_completed_count"].as<int32_t>());
        }
        if(!r["changed_at"].isNull())
        {
            auto timeStr = r["changed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(r["project_id"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            taskCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ProjectMetricsHistory::ProjectMetricsHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            taskCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

ProjectMetricsHistory::ProjectMetricsHistory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("date"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["date"].isNull())
        {
            auto daysStr = pJson["date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("task_count"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["task_count"].isNull())
        {
            taskCount_=std::make_shared<int32_t>((int32_t)pJson["task_count"].asInt64());
        }
    }
    if(pJson.isMember("task_added_count"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["task_added_count"].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>((int32_t)pJson["task_added_count"].asInt64());
        }
    }
    if(pJson.isMember("task_completed_count"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["task_completed_count"].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>((int32_t)pJson["task_completed_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_count"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["milestone_count"].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_added_count"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["milestone_added_count"].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_added_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_completed_count"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["milestone_completed_count"].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_completed_count"].asInt64());
        }
    }
    if(pJson.isMember("changed_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["changed_at"].isNull())
        {
            auto timeStr = pJson["changed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
}

void ProjectMetricsHistory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            taskCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

void ProjectMetricsHistory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("date"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["date"].isNull())
        {
            auto daysStr = pJson["date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("task_count"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["task_count"].isNull())
        {
            taskCount_=std::make_shared<int32_t>((int32_t)pJson["task_count"].asInt64());
        }
    }
    if(pJson.isMember("task_added_count"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["task_added_count"].isNull())
        {
            taskAddedCount_=std::make_shared<int32_t>((int32_t)pJson["task_added_count"].asInt64());
        }
    }
    if(pJson.isMember("task_completed_count"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["task_completed_count"].isNull())
        {
            taskCompletedCount_=std::make_shared<int32_t>((int32_t)pJson["task_completed_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_count"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["milestone_count"].isNull())
        {
            milestoneCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_added_count"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["milestone_added_count"].isNull())
        {
            milestoneAddedCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_added_count"].asInt64());
        }
    }
    if(pJson.isMember("milestone_completed_count"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["milestone_completed_count"].isNull())
        {
            milestoneCompletedCount_=std::make_shared<int32_t>((int32_t)pJson["milestone_completed_count"].asInt64());
        }
    }
    if(pJson.isMember("changed_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["changed_at"].isNull())
        {
            auto timeStr = pJson["changed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                changedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
}

const std::string &ProjectMetricsHistory::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectMetricsHistory::getId() const noexcept
{
    return id_;
}
void ProjectMetricsHistory::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ProjectMetricsHistory::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ProjectMetricsHistory::PrimaryKeyType & ProjectMetricsHistory::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const ::trantor::Date &ProjectMetricsHistory::getValueOfDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(date_)
        return *date_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectMetricsHistory::getDate() const noexcept
{
    return date_;
}
void ProjectMetricsHistory::setDate(const ::trantor::Date &pDate) noexcept
{
    date_ = std::make_shared<::trantor::Date>(pDate.roundDay());
    dirtyFlag_[1] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfTaskCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(taskCount_)
        return *taskCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getTaskCount() const noexcept
{
    return taskCount_;
}
void ProjectMetricsHistory::setTaskCount(const int32_t &pTaskCount) noexcept
{
    taskCount_ = std::make_shared<int32_t>(pTaskCount);
    dirtyFlag_[2] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfTaskAddedCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(taskAddedCount_)
        return *taskAddedCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getTaskAddedCount() const noexcept
{
    return taskAddedCount_;
}
void ProjectMetricsHistory::setTaskAddedCount(const int32_t &pTaskAddedCount) noexcept
{
    taskAddedCount_ = std::make_shared<int32_t>(pTaskAddedCount);
    dirtyFlag_[3] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfTaskCompletedCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(taskCompletedCount_)
        return *taskCompletedCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getTaskCompletedCount() const noexcept
{
    return taskCompletedCount_;
}
void ProjectMetricsHistory::setTaskCompletedCount(const int32_t &pTaskCompletedCount) noexcept
{
    taskCompletedCount_ = std::make_shared<int32_t>(pTaskCompletedCount);
    dirtyFlag_[4] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfMilestoneCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(milestoneCount_)
        return *milestoneCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getMilestoneCount() const noexcept
{
    return milestoneCount_;
}
void ProjectMetricsHistory::setMilestoneCount(const int32_t &pMilestoneCount) noexcept
{
    milestoneCount_ = std::make_shared<int32_t>(pMilestoneCount);
    dirtyFlag_[5] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfMilestoneAddedCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(milestoneAddedCount_)
        return *milestoneAddedCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getMilestoneAddedCount() const noexcept
{
    return milestoneAddedCount_;
}
void ProjectMetricsHistory::setMilestoneAddedCount(const int32_t &pMilestoneAddedCount) noexcept
{
    milestoneAddedCount_ = std::make_shared<int32_t>(pMilestoneAddedCount);
    dirtyFlag_[6] = true;
}

const int32_t &ProjectMetricsHistory::getValueOfMilestoneCompletedCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(milestoneCompletedCount_)
        return *milestoneCompletedCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectMetricsHistory::getMilestoneCompletedCount() const noexcept
{
    return milestoneCompletedCount_;
}
void ProjectMetricsHistory::setMilestoneCompletedCount(const int32_t &pMilestoneCompletedCount) noexcept
{
    milestoneCompletedCount_ = std::make_shared<int32_t>(pMilestoneCompletedCount);
    dirtyFlag_[7] = true;
}

const ::trantor::Date &ProjectMetricsHistory::getValueOfChangedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(changedAt_)
        return *changedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectMetricsHistory::getChangedAt() const noexcept
{
    return changedAt_;
}
void ProjectMetricsHistory::setChangedAt(const ::trantor::Date &pChangedAt) noexcept
{
    changedAt_ = std::make_shared<::trantor::Date>(pChangedAt);
    dirtyFlag_[8] = true;
}

const std::string &ProjectMetricsHistory::getValueOfProjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectMetricsHistory::getProjectId() const noexcept
{
    return projectId_;
}
void ProjectMetricsHistory::setProjectId(const std::string &pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(pProjectId);
    dirtyFlag_[9] = true;
}
void ProjectMetricsHistory::setProjectId(std::string &&pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(std::move(pProjectId));
    dirtyFlag_[9] = true;
}

void ProjectMetricsHistory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ProjectMetricsHistory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "date",
        "task_count",
        "task_added_count",
        "task_completed_count",
        "milestone_count",
        "milestone_added_count",
        "milestone_completed_count",
        "changed_at",
        "project_id"
    };
    return inCols;
}

void ProjectMetricsHistory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getDate())
        {
            binder << getValueOfDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTaskCount())
        {
            binder << getValueOfTaskCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTaskAddedCount())
        {
            binder << getValueOfTaskAddedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTaskCompletedCount())
        {
            binder << getValueOfTaskCompletedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMilestoneCount())
        {
            binder << getValueOfMilestoneCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMilestoneAddedCount())
        {
            binder << getValueOfMilestoneAddedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMilestoneCompletedCount())
        {
            binder << getValueOfMilestoneCompletedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getChangedAt())
        {
            binder << getValueOfChangedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ProjectMetricsHistory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void ProjectMetricsHistory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getDate())
        {
            binder << getValueOfDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTaskCount())
        {
            binder << getValueOfTaskCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTaskAddedCount())
        {
            binder << getValueOfTaskAddedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTaskCompletedCount())
        {
            binder << getValueOfTaskCompletedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMilestoneCount())
        {
            binder << getValueOfMilestoneCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMilestoneAddedCount())
        {
            binder << getValueOfMilestoneAddedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMilestoneCompletedCount())
        {
            binder << getValueOfMilestoneCompletedCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getChangedAt())
        {
            binder << getValueOfChangedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ProjectMetricsHistory::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDate())
    {
        ret["date"]=getDate()->toDbStringLocal();
    }
    else
    {
        ret["date"]=Json::Value();
    }
    if(getTaskCount())
    {
        ret["task_count"]=getValueOfTaskCount();
    }
    else
    {
        ret["task_count"]=Json::Value();
    }
    if(getTaskAddedCount())
    {
        ret["task_added_count"]=getValueOfTaskAddedCount();
    }
    else
    {
        ret["task_added_count"]=Json::Value();
    }
    if(getTaskCompletedCount())
    {
        ret["task_completed_count"]=getValueOfTaskCompletedCount();
    }
    else
    {
        ret["task_completed_count"]=Json::Value();
    }
    if(getMilestoneCount())
    {
        ret["milestone_count"]=getValueOfMilestoneCount();
    }
    else
    {
        ret["milestone_count"]=Json::Value();
    }
    if(getMilestoneAddedCount())
    {
        ret["milestone_added_count"]=getValueOfMilestoneAddedCount();
    }
    else
    {
        ret["milestone_added_count"]=Json::Value();
    }
    if(getMilestoneCompletedCount())
    {
        ret["milestone_completed_count"]=getValueOfMilestoneCompletedCount();
    }
    else
    {
        ret["milestone_completed_count"]=Json::Value();
    }
    if(getChangedAt())
    {
        ret["changed_at"]=getChangedAt()->toDbStringLocal();
    }
    else
    {
        ret["changed_at"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    return ret;
}

std::string ProjectMetricsHistory::toString() const
{
    return toJson().toStyledString();
}

Json::Value ProjectMetricsHistory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDate())
            {
                ret[pMasqueradingVector[1]]=getDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTaskCount())
            {
                ret[pMasqueradingVector[2]]=getValueOfTaskCount();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTaskAddedCount())
            {
                ret[pMasqueradingVector[3]]=getValueOfTaskAddedCount();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTaskCompletedCount())
            {
                ret[pMasqueradingVector[4]]=getValueOfTaskCompletedCount();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getMilestoneCount())
            {
                ret[pMasqueradingVector[5]]=getValueOfMilestoneCount();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMilestoneAddedCount())
            {
                ret[pMasqueradingVector[6]]=getValueOfMilestoneAddedCount();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getMilestoneCompletedCount())
            {
                ret[pMasqueradingVector[7]]=getValueOfMilestoneCompletedCount();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getChangedAt())
            {
                ret[pMasqueradingVector[8]]=getChangedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[9]]=getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDate())
    {
        ret["date"]=getDate()->toDbStringLocal();
    }
    else
    {
        ret["date"]=Json::Value();
    }
    if(getTaskCount())
    {
        ret["task_count"]=getValueOfTaskCount();
    }
    else
    {
        ret["task_count"]=Json::Value();
    }
    if(getTaskAddedCount())
    {
        ret["task_added_count"]=getValueOfTaskAddedCount();
    }
    else
    {
        ret["task_added_count"]=Json::Value();
    }
    if(getTaskCompletedCount())
    {
        ret["task_completed_count"]=getValueOfTaskCompletedCount();
    }
    else
    {
        ret["task_completed_count"]=Json::Value();
    }
    if(getMilestoneCount())
    {
        ret["milestone_count"]=getValueOfMilestoneCount();
    }
    else
    {
        ret["milestone_count"]=Json::Value();
    }
    if(getMilestoneAddedCount())
    {
        ret["milestone_added_count"]=getValueOfMilestoneAddedCount();
    }
    else
    {
        ret["milestone_added_count"]=Json::Value();
    }
    if(getMilestoneCompletedCount())
    {
        ret["milestone_completed_count"]=getValueOfMilestoneCompletedCount();
    }
    else
    {
        ret["milestone_completed_count"]=Json::Value();
    }
    if(getChangedAt())
    {
        ret["changed_at"]=getChangedAt()->toDbStringLocal();
    }
    else
    {
        ret["changed_at"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    return ret;
}

bool ProjectMetricsHistory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("date"))
    {
        if(!validJsonOfField(1, "date", pJson["date"], err, true))
            return false;
    }
    else
    {
        err="The date column cannot be null";
        return false;
    }
    if(pJson.isMember("task_count"))
    {
        if(!validJsonOfField(2, "task_count", pJson["task_count"], err, true))
            return false;
    }
    else
    {
        err="The task_count column cannot be null";
        return false;
    }
    if(pJson.isMember("task_added_count"))
    {
        if(!validJsonOfField(3, "task_added_count", pJson["task_added_count"], err, true))
            return false;
    }
    else
    {
        err="The task_added_count column cannot be null";
        return false;
    }
    if(pJson.isMember("task_completed_count"))
    {
        if(!validJsonOfField(4, "task_completed_count", pJson["task_completed_count"], err, true))
            return false;
    }
    else
    {
        err="The task_completed_count column cannot be null";
        return false;
    }
    if(pJson.isMember("milestone_count"))
    {
        if(!validJsonOfField(5, "milestone_count", pJson["milestone_count"], err, true))
            return false;
    }
    else
    {
        err="The milestone_count column cannot be null";
        return false;
    }
    if(pJson.isMember("milestone_added_count"))
    {
        if(!validJsonOfField(6, "milestone_added_count", pJson["milestone_added_count"], err, true))
            return false;
    }
    else
    {
        err="The milestone_added_count column cannot be null";
        return false;
    }
    if(pJson.isMember("milestone_completed_count"))
    {
        if(!validJsonOfField(7, "milestone_completed_count", pJson["milestone_completed_count"], err, true))
            return false;
    }
    else
    {
        err="The milestone_completed_count column cannot be null";
        return false;
    }
    if(pJson.isMember("changed_at"))
    {
        if(!validJsonOfField(8, "changed_at", pJson["changed_at"], err, true))
            return false;
    }
    else
    {
        err="The changed_at column cannot be null";
        return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(9, "project_id", pJson["project_id"], err, true))
            return false;
    }
    else
    {
        err="The project_id column cannot be null";
        return false;
    }
    return true;
}
bool ProjectMetricsHistory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectMetricsHistory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("date"))
    {
        if(!validJsonOfField(1, "date", pJson["date"], err, false))
            return false;
    }
    if(pJson.isMember("task_count"))
    {
        if(!validJsonOfField(2, "task_count", pJson["task_count"], err, false))
            return false;
    }
    if(pJson.isMember("task_added_count"))
    {
        if(!validJsonOfField(3, "task_added_count", pJson["task_added_count"], err, false))
            return false;
    }
    if(pJson.isMember("task_completed_count"))
    {
        if(!validJsonOfField(4, "task_completed_count", pJson["task_completed_count"], err, false))
            return false;
    }
    if(pJson.isMember("milestone_count"))
    {
        if(!validJsonOfField(5, "milestone_count", pJson["milestone_count"], err, false))
            return false;
    }
    if(pJson.isMember("milestone_added_count"))
    {
        if(!validJsonOfField(6, "milestone_added_count", pJson["milestone_added_count"], err, false))
            return false;
    }
    if(pJson.isMember("milestone_completed_count"))
    {
        if(!validJsonOfField(7, "milestone_completed_count", pJson["milestone_completed_count"], err, false))
            return false;
    }
    if(pJson.isMember("changed_at"))
    {
        if(!validJsonOfField(8, "changed_at", pJson["changed_at"], err, false))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(9, "project_id", pJson["project_id"], err, false))
            return false;
    }
    return true;
}
bool ProjectMetricsHistory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectMetricsHistory::validJsonOfField(size_t index,
                                             const std::string &fieldName,
                                             const Json::Value &pJson,
                                             std::string &err,
                                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
