/**
 *
 *  PullRequestSyncCheckpoints.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PullRequestSyncCheckpoints.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string PullRequestSyncCheckpoints::Cols::_repo_id = "\"repo_id\"";
const std::string PullRequestSyncCheckpoints::Cols::_repo_name = "\"repo_name\"";
const std::string PullRequestSyncCheckpoints::Cols::_last_updated_at = "\"last_updated_at\"";
const std::string PullRequestSyncCheckpoints::Cols::_last_pr_id = "\"last_pr_id\"";
const std::string PullRequestSyncCheckpoints::primaryKeyName = "repo_id";
const bool PullRequestSyncCheckpoints::hasPrimaryKey = true;
const std::string PullRequestSyncCheckpoints::tableName = "\"pull_request_sync_checkpoints\"";

const std::vector<typename PullRequestSyncCheckpoints::MetaData> PullRequestSyncCheckpoints::metaData_={
{"repo_id","int64_t","bigint",8,0,1,1},
{"repo_name","std::string","text",0,0,0,1},
{"last_updated_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"last_pr_id","int64_t","bigint",8,0,0,1}
};
const std::string &PullRequestSyncCheckpoints::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PullRequestSyncCheckpoints::PullRequestSyncCheckpoints(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["repo_id"].isNull())
        {
            repoId_=std::make_shared<int64_t>(r["repo_id"].as<int64_t>());
        }
        if(!r["repo_name"].isNull())
        {
            repoName_=std::make_shared<std::string>(r["repo_name"].as<std::string>());
        }
        if(!r["last_updated_at"].isNull())
        {
            auto timeStr = r["last_updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["last_pr_id"].isNull())
        {
            lastPrId_=std::make_shared<int64_t>(r["last_pr_id"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            repoId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            repoName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            lastPrId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

PullRequestSyncCheckpoints::PullRequestSyncCheckpoints(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            repoId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            repoName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lastPrId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

PullRequestSyncCheckpoints::PullRequestSyncCheckpoints(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("repo_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["repo_id"].isNull())
        {
            repoId_=std::make_shared<int64_t>((int64_t)pJson["repo_id"].asInt64());
        }
    }
    if(pJson.isMember("repo_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["repo_name"].isNull())
        {
            repoName_=std::make_shared<std::string>(pJson["repo_name"].asString());
        }
    }
    if(pJson.isMember("last_updated_at"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["last_updated_at"].isNull())
        {
            auto timeStr = pJson["last_updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_pr_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["last_pr_id"].isNull())
        {
            lastPrId_=std::make_shared<int64_t>((int64_t)pJson["last_pr_id"].asInt64());
        }
    }
}

void PullRequestSyncCheckpoints::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            repoId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            repoName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lastPrId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void PullRequestSyncCheckpoints::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("repo_id"))
    {
        if(!pJson["repo_id"].isNull())
        {
            repoId_=std::make_shared<int64_t>((int64_t)pJson["repo_id"].asInt64());
        }
    }
    if(pJson.isMember("repo_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["repo_name"].isNull())
        {
            repoName_=std::make_shared<std::string>(pJson["repo_name"].asString());
        }
    }
    if(pJson.isMember("last_updated_at"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["last_updated_at"].isNull())
        {
            auto timeStr = pJson["last_updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_pr_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["last_pr_id"].isNull())
        {
            lastPrId_=std::make_shared<int64_t>((int64_t)pJson["last_pr_id"].asInt64());
        }
    }
}

const int64_t &PullRequestSyncCheckpoints::getValueOfRepoId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(repoId_)
        return *repoId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PullRequestSyncCheckpoints::getRepoId() const noexcept
{
    return repoId_;
}
void PullRequestSyncCheckpoints::setRepoId(const int64_t &pRepoId) noexcept
{
    repoId_ = std::make_shared<int64_t>(pRepoId);
    dirtyFlag_[0] = true;
}
const typename PullRequestSyncCheckpoints::PrimaryKeyType & PullRequestSyncCheckpoints::getPrimaryKey() const
{
    assert(repoId_);
    return *repoId_;
}

const std::string &PullRequestSyncCheckpoints::getValueOfRepoName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(repoName_)
        return *repoName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PullRequestSyncCheckpoints::getRepoName() const noexcept
{
    return repoName_;
}
void PullRequestSyncCheckpoints::setRepoName(const std::string &pRepoName) noexcept
{
    repoName_ = std::make_shared<std::string>(pRepoName);
    dirtyFlag_[1] = true;
}
void PullRequestSyncCheckpoints::setRepoName(std::string &&pRepoName) noexcept
{
    repoName_ = std::make_shared<std::string>(std::move(pRepoName));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &PullRequestSyncCheckpoints::getValueOfLastUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastUpdatedAt_)
        return *lastUpdatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PullRequestSyncCheckpoints::getLastUpdatedAt() const noexcept
{
    return lastUpdatedAt_;
}
void PullRequestSyncCheckpoints::setLastUpdatedAt(const ::trantor::Date &pLastUpdatedAt) noexcept
{
    lastUpdatedAt_ = std::make_shared<::trantor::Date>(pLastUpdatedAt);
    dirtyFlag_[2] = true;
}

const int64_t &PullRequestSyncCheckpoints::getValueOfLastPrId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(lastPrId_)
        return *lastPrId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PullRequestSyncCheckpoints::getLastPrId() const noexcept
{
    return lastPrId_;
}
void PullRequestSyncCheckpoints::setLastPrId(const int64_t &pLastPrId) noexcept
{
    lastPrId_ = std::make_shared<int64_t>(pLastPrId);
    dirtyFlag_[3] = true;
}

void PullRequestSyncCheckpoints::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PullRequestSyncCheckpoints::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "repo_id",
        "repo_name",
        "last_updated_at",
        "last_pr_id"
    };
    return inCols;
}

void PullRequestSyncCheckpoints::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getRepoId())
        {
            binder << getValueOfRepoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRepoName())
        {
            binder << getValueOfRepoName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLastUpdatedAt())
        {
            binder << getValueOfLastUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLastPrId())
        {
            binder << getValueOfLastPrId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PullRequestSyncCheckpoints::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void PullRequestSyncCheckpoints::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getRepoId())
        {
            binder << getValueOfRepoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRepoName())
        {
            binder << getValueOfRepoName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLastUpdatedAt())
        {
            binder << getValueOfLastUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLastPrId())
        {
            binder << getValueOfLastPrId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PullRequestSyncCheckpoints::toJson() const
{
    Json::Value ret;
    if(getRepoId())
    {
        ret["repo_id"]=(Json::Int64)getValueOfRepoId();
    }
    else
    {
        ret["repo_id"]=Json::Value();
    }
    if(getRepoName())
    {
        ret["repo_name"]=getValueOfRepoName();
    }
    else
    {
        ret["repo_name"]=Json::Value();
    }
    if(getLastUpdatedAt())
    {
        ret["last_updated_at"]=getLastUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_updated_at"]=Json::Value();
    }
    if(getLastPrId())
    {
        ret["last_pr_id"]=(Json::Int64)getValueOfLastPrId();
    }
    else
    {
        ret["last_pr_id"]=Json::Value();
    }
    return ret;
}

std::string PullRequestSyncCheckpoints::toString() const
{
    return toJson().toStyledString();
}

Json::Value PullRequestSyncCheckpoints::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getRepoId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfRepoId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRepoName())
            {
                ret[pMasqueradingVector[1]]=getValueOfRepoName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLastUpdatedAt())
            {
                ret[pMasqueradingVector[2]]=getLastUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLastPrId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfLastPrId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getRepoId())
    {
        ret["repo_id"]=(Json::Int64)getValueOfRepoId();
    }
    else
    {
        ret["repo_id"]=Json::Value();
    }
    if(getRepoName())
    {
        ret["repo_name"]=getValueOfRepoName();
    }
    else
    {
        ret["repo_name"]=Json::Value();
    }
    if(getLastUpdatedAt())
    {
        ret["last_updated_at"]=getLastUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["last_updated_at"]=Json::Value();
    }
    if(getLastPrId())
    {
        ret["last_pr_id"]=(Json::Int64)getValueOfLastPrId();
    }
    else
    {
        ret["last_pr_id"]=Json::Value();
    }
    return ret;
}

bool PullRequestSyncCheckpoints::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("repo_id"))
    {
        if(!validJsonOfField(0, "repo_id", pJson["repo_id"], err, true))
            return false;
    }
    else
    {
        err="The repo_id column cannot be null";
        return false;
    }
    if(pJson.isMember("repo_name"))
    {
        if(!validJsonOfField(1, "repo_name", pJson["repo_name"], err, true))
            return false;
    }
    else
    {
        err="The repo_name column cannot be null";
        return false;
    }
    if(pJson.isMember("last_updated_at"))
    {
        if(!validJsonOfField(2, "last_updated_at", pJson["last_updated_at"], err, true))
            return false;
    }
    else
    {
        err="The last_updated_at column cannot be null";
        return false;
    }
    if(pJson.isMember("last_pr_id"))
    {
        if(!validJsonOfField(3, "last_pr_id", pJson["last_pr_id"], err, true))
            return false;
    }
    else
    {
        err="The last_pr_id column cannot be null";
        return false;
    }
    return true;
}
bool PullRequestSyncCheckpoints::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                    const std::vector<std::string> &pMasqueradingVector,
                                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PullRequestSyncCheckpoints::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("repo_id"))
    {
        if(!validJsonOfField(0, "repo_id", pJson["repo_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("repo_name"))
    {
        if(!validJsonOfField(1, "repo_name", pJson["repo_name"], err, false))
            return false;
    }
    if(pJson.isMember("last_updated_at"))
    {
        if(!validJsonOfField(2, "last_updated_at", pJson["last_updated_at"], err, false))
            return false;
    }
    if(pJson.isMember("last_pr_id"))
    {
        if(!validJsonOfField(3, "last_pr_id", pJson["last_pr_id"], err, false))
            return false;
    }
    return true;
}
bool PullRequestSyncCheckpoints::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                  const std::vector<std::string> &pMasqueradingVector,
                                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PullRequestSyncCheckpoints::validJsonOfField(size_t index,
                                                  const std::string &fieldName,
                                                  const Json::Value &pJson,
                                                  std::string &err,
                                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
