/**
 *
 *  Tasks.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace teams_manager
{

class Tasks
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _creator_id;
        static const std::string _creator_name;
        static const std::string _tenant_id;
        static const std::string _tenant_name;
        static const std::string _project_id;
        static const std::string _project_name;
        static const std::string _task_type_id;
        static const std::string _task_type_name;
        static const std::string _name;
        static const std::string _excecutor_time_ratio;
        static const std::string _description;
        static const std::string _concurrency_stamp;
        static const std::string _created_at;
        static const std::string _remark;
        static const std::string _scheduled_start_date;
        static const std::string _scheduled_end_date;
        static const std::string _scheduled_completion_date;
        static const std::string _completion_date;
        static const std::string _progress;
        static const std::string _completed;
        static const std::string _status_id;
        static const std::string _status_name;
        static const std::string _status_last_changed;
        static const std::string _result_description;
        static const std::string _team_id;
        static const std::string _team_name;
        static const std::string _milestone_id;
        static const std::string _milestone_name;
        static const std::string _delayed;
        static const std::string _estimated_workdays;
        static const std::string _priority;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Tasks(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Tasks(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Tasks(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Tasks() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column creator_id  */
    ///Get the value of the column creator_id, returns the default value if the column is null
    const std::string &getValueOfCreatorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatorId() const noexcept;
    ///Set the value of the column creator_id
    void setCreatorId(const std::string &pCreatorId) noexcept;
    void setCreatorId(std::string &&pCreatorId) noexcept;

    /**  For column creator_name  */
    ///Get the value of the column creator_name, returns the default value if the column is null
    const std::string &getValueOfCreatorName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatorName() const noexcept;
    ///Set the value of the column creator_name
    void setCreatorName(const std::string &pCreatorName) noexcept;
    void setCreatorName(std::string &&pCreatorName) noexcept;

    /**  For column tenant_id  */
    ///Get the value of the column tenant_id, returns the default value if the column is null
    const std::string &getValueOfTenantId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTenantId() const noexcept;
    ///Set the value of the column tenant_id
    void setTenantId(const std::string &pTenantId) noexcept;
    void setTenantId(std::string &&pTenantId) noexcept;
    void setTenantIdToNull() noexcept;

    /**  For column tenant_name  */
    ///Get the value of the column tenant_name, returns the default value if the column is null
    const std::string &getValueOfTenantName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTenantName() const noexcept;
    ///Set the value of the column tenant_name
    void setTenantName(const std::string &pTenantName) noexcept;
    void setTenantName(std::string &&pTenantName) noexcept;
    void setTenantNameToNull() noexcept;

    /**  For column project_id  */
    ///Get the value of the column project_id, returns the default value if the column is null
    const std::string &getValueOfProjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectId() const noexcept;
    ///Set the value of the column project_id
    void setProjectId(const std::string &pProjectId) noexcept;
    void setProjectId(std::string &&pProjectId) noexcept;
    void setProjectIdToNull() noexcept;

    /**  For column project_name  */
    ///Get the value of the column project_name, returns the default value if the column is null
    const std::string &getValueOfProjectName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectName() const noexcept;
    ///Set the value of the column project_name
    void setProjectName(const std::string &pProjectName) noexcept;
    void setProjectName(std::string &&pProjectName) noexcept;
    void setProjectNameToNull() noexcept;

    /**  For column task_type_id  */
    ///Get the value of the column task_type_id, returns the default value if the column is null
    const std::string &getValueOfTaskTypeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaskTypeId() const noexcept;
    ///Set the value of the column task_type_id
    void setTaskTypeId(const std::string &pTaskTypeId) noexcept;
    void setTaskTypeId(std::string &&pTaskTypeId) noexcept;
    void setTaskTypeIdToNull() noexcept;

    /**  For column task_type_name  */
    ///Get the value of the column task_type_name, returns the default value if the column is null
    const std::string &getValueOfTaskTypeName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaskTypeName() const noexcept;
    ///Set the value of the column task_type_name
    void setTaskTypeName(const std::string &pTaskTypeName) noexcept;
    void setTaskTypeName(std::string &&pTaskTypeName) noexcept;
    void setTaskTypeNameToNull() noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column excecutor_time_ratio  */
    ///Get the value of the column excecutor_time_ratio, returns the default value if the column is null
    const double &getValueOfExcecutorTimeRatio() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getExcecutorTimeRatio() const noexcept;
    ///Set the value of the column excecutor_time_ratio
    void setExcecutorTimeRatio(const double &pExcecutorTimeRatio) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column concurrency_stamp  */
    ///Get the value of the column concurrency_stamp, returns the default value if the column is null
    const std::string &getValueOfConcurrencyStamp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getConcurrencyStamp() const noexcept;
    ///Set the value of the column concurrency_stamp
    void setConcurrencyStamp(const std::string &pConcurrencyStamp) noexcept;
    void setConcurrencyStamp(std::string &&pConcurrencyStamp) noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column remark  */
    ///Get the value of the column remark, returns the default value if the column is null
    const std::string &getValueOfRemark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRemark() const noexcept;
    ///Set the value of the column remark
    void setRemark(const std::string &pRemark) noexcept;
    void setRemark(std::string &&pRemark) noexcept;
    void setRemarkToNull() noexcept;

    /**  For column scheduled_start_date  */
    ///Get the value of the column scheduled_start_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfScheduledStartDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getScheduledStartDate() const noexcept;
    ///Set the value of the column scheduled_start_date
    void setScheduledStartDate(const ::trantor::Date &pScheduledStartDate) noexcept;
    void setScheduledStartDateToNull() noexcept;

    /**  For column scheduled_end_date  */
    ///Get the value of the column scheduled_end_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfScheduledEndDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getScheduledEndDate() const noexcept;
    ///Set the value of the column scheduled_end_date
    void setScheduledEndDate(const ::trantor::Date &pScheduledEndDate) noexcept;
    void setScheduledEndDateToNull() noexcept;

    /**  For column scheduled_completion_date  */
    ///Get the value of the column scheduled_completion_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfScheduledCompletionDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getScheduledCompletionDate() const noexcept;
    ///Set the value of the column scheduled_completion_date
    void setScheduledCompletionDate(const ::trantor::Date &pScheduledCompletionDate) noexcept;
    void setScheduledCompletionDateToNull() noexcept;

    /**  For column completion_date  */
    ///Get the value of the column completion_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfCompletionDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCompletionDate() const noexcept;
    ///Set the value of the column completion_date
    void setCompletionDate(const ::trantor::Date &pCompletionDate) noexcept;
    void setCompletionDateToNull() noexcept;

    /**  For column progress  */
    ///Get the value of the column progress, returns the default value if the column is null
    const std::string &getValueOfProgress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProgress() const noexcept;
    ///Set the value of the column progress
    void setProgress(const std::string &pProgress) noexcept;
    void setProgress(std::string &&pProgress) noexcept;

    /**  For column completed  */
    ///Get the value of the column completed, returns the default value if the column is null
    const bool &getValueOfCompleted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getCompleted() const noexcept;
    ///Set the value of the column completed
    void setCompleted(const bool &pCompleted) noexcept;

    /**  For column status_id  */
    ///Get the value of the column status_id, returns the default value if the column is null
    const std::string &getValueOfStatusId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatusId() const noexcept;
    ///Set the value of the column status_id
    void setStatusId(const std::string &pStatusId) noexcept;
    void setStatusId(std::string &&pStatusId) noexcept;

    /**  For column status_name  */
    ///Get the value of the column status_name, returns the default value if the column is null
    const std::string &getValueOfStatusName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatusName() const noexcept;
    ///Set the value of the column status_name
    void setStatusName(const std::string &pStatusName) noexcept;
    void setStatusName(std::string &&pStatusName) noexcept;

    /**  For column status_last_changed  */
    ///Get the value of the column status_last_changed, returns the default value if the column is null
    const ::trantor::Date &getValueOfStatusLastChanged() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getStatusLastChanged() const noexcept;
    ///Set the value of the column status_last_changed
    void setStatusLastChanged(const ::trantor::Date &pStatusLastChanged) noexcept;

    /**  For column result_description  */
    ///Get the value of the column result_description, returns the default value if the column is null
    const std::string &getValueOfResultDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getResultDescription() const noexcept;
    ///Set the value of the column result_description
    void setResultDescription(const std::string &pResultDescription) noexcept;
    void setResultDescription(std::string &&pResultDescription) noexcept;
    void setResultDescriptionToNull() noexcept;

    /**  For column team_id  */
    ///Get the value of the column team_id, returns the default value if the column is null
    const std::string &getValueOfTeamId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeamId() const noexcept;
    ///Set the value of the column team_id
    void setTeamId(const std::string &pTeamId) noexcept;
    void setTeamId(std::string &&pTeamId) noexcept;
    void setTeamIdToNull() noexcept;

    /**  For column team_name  */
    ///Get the value of the column team_name, returns the default value if the column is null
    const std::string &getValueOfTeamName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeamName() const noexcept;
    ///Set the value of the column team_name
    void setTeamName(const std::string &pTeamName) noexcept;
    void setTeamName(std::string &&pTeamName) noexcept;
    void setTeamNameToNull() noexcept;

    /**  For column milestone_id  */
    ///Get the value of the column milestone_id, returns the default value if the column is null
    const std::string &getValueOfMilestoneId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMilestoneId() const noexcept;
    ///Set the value of the column milestone_id
    void setMilestoneId(const std::string &pMilestoneId) noexcept;
    void setMilestoneId(std::string &&pMilestoneId) noexcept;
    void setMilestoneIdToNull() noexcept;

    /**  For column milestone_name  */
    ///Get the value of the column milestone_name, returns the default value if the column is null
    const std::string &getValueOfMilestoneName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMilestoneName() const noexcept;
    ///Set the value of the column milestone_name
    void setMilestoneName(const std::string &pMilestoneName) noexcept;
    void setMilestoneName(std::string &&pMilestoneName) noexcept;
    void setMilestoneNameToNull() noexcept;

    /**  For column delayed  */
    ///Get the value of the column delayed, returns the default value if the column is null
    const bool &getValueOfDelayed() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getDelayed() const noexcept;
    ///Set the value of the column delayed
    void setDelayed(const bool &pDelayed) noexcept;

    /**  For column estimated_workdays  */
    ///Get the value of the column estimated_workdays, returns the default value if the column is null
    const int32_t &getValueOfEstimatedWorkdays() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEstimatedWorkdays() const noexcept;
    ///Set the value of the column estimated_workdays
    void setEstimatedWorkdays(const int32_t &pEstimatedWorkdays) noexcept;

    /**  For column priority  */
    ///Get the value of the column priority, returns the default value if the column is null
    const int32_t &getValueOfPriority() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPriority() const noexcept;
    ///Set the value of the column priority
    void setPriority(const int32_t &pPriority) noexcept;


    static size_t getColumnNumber() noexcept {  return 32;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Tasks>;
    friend drogon::orm::BaseBuilder<Tasks, true, true>;
    friend drogon::orm::BaseBuilder<Tasks, true, false>;
    friend drogon::orm::BaseBuilder<Tasks, false, true>;
    friend drogon::orm::BaseBuilder<Tasks, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Tasks>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> creatorId_;
    std::shared_ptr<std::string> creatorName_;
    std::shared_ptr<std::string> tenantId_;
    std::shared_ptr<std::string> tenantName_;
    std::shared_ptr<std::string> projectId_;
    std::shared_ptr<std::string> projectName_;
    std::shared_ptr<std::string> taskTypeId_;
    std::shared_ptr<std::string> taskTypeName_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<double> excecutorTimeRatio_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> concurrencyStamp_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<std::string> remark_;
    std::shared_ptr<::trantor::Date> scheduledStartDate_;
    std::shared_ptr<::trantor::Date> scheduledEndDate_;
    std::shared_ptr<::trantor::Date> scheduledCompletionDate_;
    std::shared_ptr<::trantor::Date> completionDate_;
    std::shared_ptr<std::string> progress_;
    std::shared_ptr<bool> completed_;
    std::shared_ptr<std::string> statusId_;
    std::shared_ptr<std::string> statusName_;
    std::shared_ptr<::trantor::Date> statusLastChanged_;
    std::shared_ptr<std::string> resultDescription_;
    std::shared_ptr<std::string> teamId_;
    std::shared_ptr<std::string> teamName_;
    std::shared_ptr<std::string> milestoneId_;
    std::shared_ptr<std::string> milestoneName_;
    std::shared_ptr<bool> delayed_;
    std::shared_ptr<int32_t> estimatedWorkdays_;
    std::shared_ptr<int32_t> priority_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[32]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "creator_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "creator_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "tenant_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "tenant_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "project_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "project_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "task_type_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "task_type_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "name,";
            ++parametersCount;
        }
        sql += "excecutor_time_ratio,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        if(dirtyFlag_[11])
        {
            sql += "description,";
            ++parametersCount;
        }
        sql += "concurrency_stamp,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        if(dirtyFlag_[14])
        {
            sql += "remark,";
            ++parametersCount;
        }
        if(dirtyFlag_[15])
        {
            sql += "scheduled_start_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[16])
        {
            sql += "scheduled_end_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[17])
        {
            sql += "scheduled_completion_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[18])
        {
            sql += "completion_date,";
            ++parametersCount;
        }
        sql += "progress,";
        ++parametersCount;
        if(!dirtyFlag_[19])
        {
            needSelection=true;
        }
        sql += "completed,";
        ++parametersCount;
        if(!dirtyFlag_[20])
        {
            needSelection=true;
        }
        if(dirtyFlag_[21])
        {
            sql += "status_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[22])
        {
            sql += "status_name,";
            ++parametersCount;
        }
        sql += "status_last_changed,";
        ++parametersCount;
        if(!dirtyFlag_[23])
        {
            needSelection=true;
        }
        if(dirtyFlag_[24])
        {
            sql += "result_description,";
            ++parametersCount;
        }
        if(dirtyFlag_[25])
        {
            sql += "team_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[26])
        {
            sql += "team_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[27])
        {
            sql += "milestone_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[28])
        {
            sql += "milestone_name,";
            ++parametersCount;
        }
        sql += "delayed,";
        ++parametersCount;
        if(!dirtyFlag_[29])
        {
            needSelection=true;
        }
        sql += "estimated_workdays,";
        ++parametersCount;
        if(!dirtyFlag_[30])
        {
            needSelection=true;
        }
        sql += "priority,";
        ++parametersCount;
        if(!dirtyFlag_[31])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[18])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[20])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[21])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[22])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[23])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[24])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[25])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[26])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[27])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[28])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[29])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[30])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[31])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace teams_manager
} // namespace drogon_model
