/**
 *
 *  WorkItemDependencies.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "WorkItemDependencies.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::teams_manager;

const std::string WorkItemDependencies::Cols::_id = "\"id\"";
const std::string WorkItemDependencies::Cols::_predecessor_type = "\"predecessor_type\"";
const std::string WorkItemDependencies::Cols::_predecessor_id = "\"predecessor_id\"";
const std::string WorkItemDependencies::Cols::_successor_type = "\"successor_type\"";
const std::string WorkItemDependencies::Cols::_successor_id = "\"successor_id\"";
const std::string WorkItemDependencies::Cols::_dependency_type = "\"dependency_type\"";
const std::string WorkItemDependencies::Cols::_created_at = "\"created_at\"";
const std::string WorkItemDependencies::primaryKeyName = "id";
const bool WorkItemDependencies::hasPrimaryKey = true;
const std::string WorkItemDependencies::tableName = "\"work_item_dependencies\"";

const std::vector<typename WorkItemDependencies::MetaData> WorkItemDependencies::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"predecessor_type","std::string","USER-DEFINED",0,0,0,1},
{"predecessor_id","std::string","uuid",0,0,0,1},
{"successor_type","std::string","USER-DEFINED",0,0,0,1},
{"successor_id","std::string","uuid",0,0,0,1},
{"dependency_type","std::string","USER-DEFINED",0,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &WorkItemDependencies::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
WorkItemDependencies::WorkItemDependencies(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["predecessor_type"].isNull())
        {
            predecessorType_=std::make_shared<std::string>(r["predecessor_type"].as<std::string>());
        }
        if(!r["predecessor_id"].isNull())
        {
            predecessorId_=std::make_shared<std::string>(r["predecessor_id"].as<std::string>());
        }
        if(!r["successor_type"].isNull())
        {
            successorType_=std::make_shared<std::string>(r["successor_type"].as<std::string>());
        }
        if(!r["successor_id"].isNull())
        {
            successorId_=std::make_shared<std::string>(r["successor_id"].as<std::string>());
        }
        if(!r["dependency_type"].isNull())
        {
            dependencyType_=std::make_shared<std::string>(r["dependency_type"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            predecessorType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            predecessorId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            successorType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            successorId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            dependencyType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

WorkItemDependencies::WorkItemDependencies(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            predecessorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            predecessorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            successorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            successorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            dependencyType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

WorkItemDependencies::WorkItemDependencies(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("predecessor_type"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["predecessor_type"].isNull())
        {
            predecessorType_=std::make_shared<std::string>(pJson["predecessor_type"].asString());
        }
    }
    if(pJson.isMember("predecessor_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["predecessor_id"].isNull())
        {
            predecessorId_=std::make_shared<std::string>(pJson["predecessor_id"].asString());
        }
    }
    if(pJson.isMember("successor_type"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["successor_type"].isNull())
        {
            successorType_=std::make_shared<std::string>(pJson["successor_type"].asString());
        }
    }
    if(pJson.isMember("successor_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["successor_id"].isNull())
        {
            successorId_=std::make_shared<std::string>(pJson["successor_id"].asString());
        }
    }
    if(pJson.isMember("dependency_type"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["dependency_type"].isNull())
        {
            dependencyType_=std::make_shared<std::string>(pJson["dependency_type"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WorkItemDependencies::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            predecessorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            predecessorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            successorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            successorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            dependencyType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WorkItemDependencies::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("predecessor_type"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["predecessor_type"].isNull())
        {
            predecessorType_=std::make_shared<std::string>(pJson["predecessor_type"].asString());
        }
    }
    if(pJson.isMember("predecessor_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["predecessor_id"].isNull())
        {
            predecessorId_=std::make_shared<std::string>(pJson["predecessor_id"].asString());
        }
    }
    if(pJson.isMember("successor_type"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["successor_type"].isNull())
        {
            successorType_=std::make_shared<std::string>(pJson["successor_type"].asString());
        }
    }
    if(pJson.isMember("successor_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["successor_id"].isNull())
        {
            successorId_=std::make_shared<std::string>(pJson["successor_id"].asString());
        }
    }
    if(pJson.isMember("dependency_type"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["dependency_type"].isNull())
        {
            dependencyType_=std::make_shared<std::string>(pJson["dependency_type"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &WorkItemDependencies::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getId() const noexcept
{
    return id_;
}
void WorkItemDependencies::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void WorkItemDependencies::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename WorkItemDependencies::PrimaryKeyType & WorkItemDependencies::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &WorkItemDependencies::getValueOfPredecessorType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(predecessorType_)
        return *predecessorType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getPredecessorType() const noexcept
{
    return predecessorType_;
}
void WorkItemDependencies::setPredecessorType(const std::string &pPredecessorType) noexcept
{
    predecessorType_ = std::make_shared<std::string>(pPredecessorType);
    dirtyFlag_[1] = true;
}
void WorkItemDependencies::setPredecessorType(std::string &&pPredecessorType) noexcept
{
    predecessorType_ = std::make_shared<std::string>(std::move(pPredecessorType));
    dirtyFlag_[1] = true;
}

const std::string &WorkItemDependencies::getValueOfPredecessorId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(predecessorId_)
        return *predecessorId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getPredecessorId() const noexcept
{
    return predecessorId_;
}
void WorkItemDependencies::setPredecessorId(const std::string &pPredecessorId) noexcept
{
    predecessorId_ = std::make_shared<std::string>(pPredecessorId);
    dirtyFlag_[2] = true;
}
void WorkItemDependencies::setPredecessorId(std::string &&pPredecessorId) noexcept
{
    predecessorId_ = std::make_shared<std::string>(std::move(pPredecessorId));
    dirtyFlag_[2] = true;
}

const std::string &WorkItemDependencies::getValueOfSuccessorType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(successorType_)
        return *successorType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getSuccessorType() const noexcept
{
    return successorType_;
}
void WorkItemDependencies::setSuccessorType(const std::string &pSuccessorType) noexcept
{
    successorType_ = std::make_shared<std::string>(pSuccessorType);
    dirtyFlag_[3] = true;
}
void WorkItemDependencies::setSuccessorType(std::string &&pSuccessorType) noexcept
{
    successorType_ = std::make_shared<std::string>(std::move(pSuccessorType));
    dirtyFlag_[3] = true;
}

const std::string &WorkItemDependencies::getValueOfSuccessorId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(successorId_)
        return *successorId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getSuccessorId() const noexcept
{
    return successorId_;
}
void WorkItemDependencies::setSuccessorId(const std::string &pSuccessorId) noexcept
{
    successorId_ = std::make_shared<std::string>(pSuccessorId);
    dirtyFlag_[4] = true;
}
void WorkItemDependencies::setSuccessorId(std::string &&pSuccessorId) noexcept
{
    successorId_ = std::make_shared<std::string>(std::move(pSuccessorId));
    dirtyFlag_[4] = true;
}

const std::string &WorkItemDependencies::getValueOfDependencyType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dependencyType_)
        return *dependencyType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItemDependencies::getDependencyType() const noexcept
{
    return dependencyType_;
}
void WorkItemDependencies::setDependencyType(const std::string &pDependencyType) noexcept
{
    dependencyType_ = std::make_shared<std::string>(pDependencyType);
    dirtyFlag_[5] = true;
}
void WorkItemDependencies::setDependencyType(std::string &&pDependencyType) noexcept
{
    dependencyType_ = std::make_shared<std::string>(std::move(pDependencyType));
    dirtyFlag_[5] = true;
}

const ::trantor::Date &WorkItemDependencies::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WorkItemDependencies::getCreatedAt() const noexcept
{
    return createdAt_;
}
void WorkItemDependencies::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[6] = true;
}

void WorkItemDependencies::updateId(const uint64_t id)
{
}

const std::vector<std::string> &WorkItemDependencies::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "predecessor_type",
        "predecessor_id",
        "successor_type",
        "successor_id",
        "dependency_type",
        "created_at"
    };
    return inCols;
}

void WorkItemDependencies::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPredecessorType())
        {
            binder << getValueOfPredecessorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPredecessorId())
        {
            binder << getValueOfPredecessorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSuccessorType())
        {
            binder << getValueOfSuccessorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSuccessorId())
        {
            binder << getValueOfSuccessorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDependencyType())
        {
            binder << getValueOfDependencyType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> WorkItemDependencies::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void WorkItemDependencies::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPredecessorType())
        {
            binder << getValueOfPredecessorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPredecessorId())
        {
            binder << getValueOfPredecessorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSuccessorType())
        {
            binder << getValueOfSuccessorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSuccessorId())
        {
            binder << getValueOfSuccessorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDependencyType())
        {
            binder << getValueOfDependencyType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value WorkItemDependencies::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPredecessorType())
    {
        ret["predecessor_type"]=getValueOfPredecessorType();
    }
    else
    {
        ret["predecessor_type"]=Json::Value();
    }
    if(getPredecessorId())
    {
        ret["predecessor_id"]=getValueOfPredecessorId();
    }
    else
    {
        ret["predecessor_id"]=Json::Value();
    }
    if(getSuccessorType())
    {
        ret["successor_type"]=getValueOfSuccessorType();
    }
    else
    {
        ret["successor_type"]=Json::Value();
    }
    if(getSuccessorId())
    {
        ret["successor_id"]=getValueOfSuccessorId();
    }
    else
    {
        ret["successor_id"]=Json::Value();
    }
    if(getDependencyType())
    {
        ret["dependency_type"]=getValueOfDependencyType();
    }
    else
    {
        ret["dependency_type"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string WorkItemDependencies::toString() const
{
    return toJson().toStyledString();
}

Json::Value WorkItemDependencies::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPredecessorType())
            {
                ret[pMasqueradingVector[1]]=getValueOfPredecessorType();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPredecessorId())
            {
                ret[pMasqueradingVector[2]]=getValueOfPredecessorId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSuccessorType())
            {
                ret[pMasqueradingVector[3]]=getValueOfSuccessorType();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSuccessorId())
            {
                ret[pMasqueradingVector[4]]=getValueOfSuccessorId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDependencyType())
            {
                ret[pMasqueradingVector[5]]=getValueOfDependencyType();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[6]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPredecessorType())
    {
        ret["predecessor_type"]=getValueOfPredecessorType();
    }
    else
    {
        ret["predecessor_type"]=Json::Value();
    }
    if(getPredecessorId())
    {
        ret["predecessor_id"]=getValueOfPredecessorId();
    }
    else
    {
        ret["predecessor_id"]=Json::Value();
    }
    if(getSuccessorType())
    {
        ret["successor_type"]=getValueOfSuccessorType();
    }
    else
    {
        ret["successor_type"]=Json::Value();
    }
    if(getSuccessorId())
    {
        ret["successor_id"]=getValueOfSuccessorId();
    }
    else
    {
        ret["successor_id"]=Json::Value();
    }
    if(getDependencyType())
    {
        ret["dependency_type"]=getValueOfDependencyType();
    }
    else
    {
        ret["dependency_type"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool WorkItemDependencies::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("predecessor_type"))
    {
        if(!validJsonOfField(1, "predecessor_type", pJson["predecessor_type"], err, true))
            return false;
    }
    else
    {
        err="The predecessor_type column cannot be null";
        return false;
    }
    if(pJson.isMember("predecessor_id"))
    {
        if(!validJsonOfField(2, "predecessor_id", pJson["predecessor_id"], err, true))
            return false;
    }
    else
    {
        err="The predecessor_id column cannot be null";
        return false;
    }
    if(pJson.isMember("successor_type"))
    {
        if(!validJsonOfField(3, "successor_type", pJson["successor_type"], err, true))
            return false;
    }
    else
    {
        err="The successor_type column cannot be null";
        return false;
    }
    if(pJson.isMember("successor_id"))
    {
        if(!validJsonOfField(4, "successor_id", pJson["successor_id"], err, true))
            return false;
    }
    else
    {
        err="The successor_id column cannot be null";
        return false;
    }
    if(pJson.isMember("dependency_type"))
    {
        if(!validJsonOfField(5, "dependency_type", pJson["dependency_type"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool WorkItemDependencies::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                              const std::vector<std::string> &pMasqueradingVector,
                                                              std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WorkItemDependencies::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("predecessor_type"))
    {
        if(!validJsonOfField(1, "predecessor_type", pJson["predecessor_type"], err, false))
            return false;
    }
    if(pJson.isMember("predecessor_id"))
    {
        if(!validJsonOfField(2, "predecessor_id", pJson["predecessor_id"], err, false))
            return false;
    }
    if(pJson.isMember("successor_type"))
    {
        if(!validJsonOfField(3, "successor_type", pJson["successor_type"], err, false))
            return false;
    }
    if(pJson.isMember("successor_id"))
    {
        if(!validJsonOfField(4, "successor_id", pJson["successor_id"], err, false))
            return false;
    }
    if(pJson.isMember("dependency_type"))
    {
        if(!validJsonOfField(5, "dependency_type", pJson["dependency_type"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool WorkItemDependencies::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WorkItemDependencies::validJsonOfField(size_t index,
                                            const std::string &fieldName,
                                            const Json::Value &pJson,
                                            std::string &err,
                                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
